<?php 
require('../commons/base.inc.php');
print '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';
print "\n".'<html xmlns="http://www.w3.org/1999/xhtml">';
print "\n<head>";
print "\n\t".'<meta http-equiv="content-type" content="text/html; charset=utf-8" />';
print "\n\t".'<meta http-equiv="x-ua-compatible" content="IE=8">';
print "\n\t".'<link href="http://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">';
print "\n\t".'<link href="../management/css/fog.css" rel="stylesheet" type="text/css" />';
print "\n\t".'<link rel="stylesheet" type="text/css" href="../management/css/fog.css" />';
print "\n\t<title>"._('FOG').' '.FOG_VERSION.' '._('client applications').'</title>';
print "\n</head>";
print "\n<body>";
print "\n\t".'<div id="wrapper">';
print "\n\t\t<!-- Header -->";
print "\n\t\t".'<div id="header">';
print "\n\t\t\t".'<div id="logo">';
print "\n\t\t\t\t".'<h1><a href="'.$_SERVER['PHP_SELF'].'"><img src="../management/images/fog-logo.png" title="'.$foglang['Home'].'" /><sup>'.FOG_VERSION.'</sup></a></h1>';
print "\n\t\t\t\t".'<h2>'.$foglang['Slogan'].'</h2>';
print "\n\t\t\t</div>";
print "\n\t\t</div>";
print "\n\t\t<!-- Content -->";
print "\n\t\t".'<div id="content" class="dashboard">';
print "\n\t\t\t<h1>"._('FOG Client Installer').'</h1>';
print "\n\t\t\t\t".'<div id="content-inner">';
print "\n\t\t\t\t\t".'<div class="dashbaord">';
print "\n\t\t\t\t\t\t".'<p class="infoTitle">'._('Client Service').'</p>';
print "\n\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t"._('Download the FOG client service. This service allows for advanced management of the PC, including hostname changing, etc...');
print "\n\t\t\t\t\t\t\t".'<br /><br />';
print "\n\t\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t\t".'<a href="FogService.zip">';
print "\n\t\t\t\t\t\t\t\t\t"._('FOG Client Service');
print "\n\t\t\t\t\t\t\t\t</a>";
print "\n\t\t\t\t\t\t\t</p>";
print "\n\t\t\t\t\t\t</p>";
print "\n\t\t\t\t\t</div>";
print "\n\t\t\t\t\t".'<div class="dashbaord">';
print "\n\t\t\t\t\t\t".'<p class="infoTitle">'._('FOG Prep').'</p>';
print "\n\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t"._('Download FOG Prep which must be run on computers running Windows 7 immediately prior to image upload.');
print "\n\t\t\t\t\t\t\t".'<br /><br /><br />';
print "\n\t\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t".'<a href="FogPrep.zip">';
print "\n\t\t\t\t\t\t\t\t"._('FOG Prep');
print "\n\t\t\t\t\t\t\t</a>";
print "\n\t\t\t\t\t\t</p>";
print "\n\t\t\t\t\t</div>";
print "\n\t\t\t\t\t".'<div class="dashbaord">';
print "\n\t\t\t\t\t\t".'<p class="infoTitle">'._('FOG Crypt').'</p>';
print "\n\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t"._('Download FOG Crypt which can be used to encrypt the AD Domain Password.');
print "\n\t\t\t\t\t\t\t".'<br /><br /><br />';
print "\n\t\t\t\t\t\t\t".'<p class="noSpace">';
print "\n\t\t\t\t\t\t\t".'<a href="FOGCrypt.zip">';
print "\n\t\t\t\t\t\t\t\t"._('FOG Crypt');
print "\n\t\t\t\t\t\t\t</a>";
print "\n\t\t\t\t\t\t</p>";
print "\n\t\t\t\t\t</div>";
print "\n\t\t\t\t</div>";
print "\n\t\t\t</div>";
print "\n\t\t</div>";
print "\n\t</div>";
print "\n\t<!-- Footer -->";
print "\n\t".'<div id="footer">FOG Project: Chuck Syperski, Jian Zhang, Peter Gilchrist &amp; Tom Elliott</div>';
print "\n</body>";
print "\n</html>";
