#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git merge" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message to
# stderr if it wants to stop the merge commit.
#
# To enable this hook, rename this file to "pre-merge-commit".
# this was taken from the example hook and adapted to run the custom hook

. git-sh-setup
test -x "$GIT_WORK_TREE/.githooks/pre-commit" &&
        exec "$GIT_WORK_TREE/.githooks/pre-commit"
:
