#!/bin/bash
#
# The boot chain must LOAD commons/config.class.php, not hope something finds it.
#
#   tests/generated-config-is-loaded.test.sh
#
# `class Config` is generated by the installer into commons/config.class.php and
# is the one .class.php file left anywhere in a deployed tree -- the only class
# in FOG that is neither PSR-4 under src/ nor inside a plugin. It was reached by
# the autoloader's recursive *.class.php scan of BASEPATH until ADR 0035 retired
# that scan, at which point `new Config()` in startInit() became
#
#     Uncaught Error: Class "Config" not found in commons/init.php
#
# on EVERY page -- a blank 500 in a browser, and the installer's own "Checking
# web server serves FOG" probe failing with 0 bytes of body.
#
# WHY NOTHING CAUGHT IT. Every PHP test in this suite constructs Initiator (which
# only registers the autoloader) and stops short of startInit(), because
# startInit() wants a database. So the entire boot tail -- including this line --
# has no coverage at all. That is the gap this file closes, and it closes it
# without a database by driving the boot in a tree whose config.class.php is a
# stub: the assertion is about which error comes back, not about reaching a page.
#
# EXECUTED, not grepped. A textual check for `require_once` near `new Config()`
# passes on a require of the wrong path, on one guarded by a condition that is
# never true, and on one placed after the use. Only running it distinguishes
# those, and each is a mutation this file was verified against.
#
# Usage: bash tests/generated-config-is-loaded.test.sh
# Exit status 0 = pass, 1 = fail.

set -uo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
web="$root/packages/web"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

fails=0
checks=0
check() {
    checks=$((checks + 1))
    if [[ $2 -ne 0 ]]; then
        echo "  - $1" >&2
        fails=$((fails + 1))
    fi
}

# A tree that is the real one everywhere except commons/, which is a real
# directory so __DIR__ resolves inside $tmp and the stub config is the one
# found. Symlinks for the rest: BASEPATH is derived from init.php's location,
# so the tree has to look complete without being copied.
mkdir -p "$tmp/web/commons"
for d in "$web"/*/; do
    name=$(basename "$d")
    [[ $name == commons ]] && continue
    ln -s "$d" "$tmp/web/$name"
done
cp "$web"/commons/*.php "$tmp/web/commons/" 2>/dev/null
[[ -d "$root/vendor" ]] && ln -s "$root/vendor" "$tmp/vendor"

# Driven through commons/base.inc.php, NOT management/index.php. index.php
# reaches its includes as ../commons/..., and PHP resolves that against the
# REAL path -- so with management/ symlinked to the shipped tree the boot ran
# against the repository's own commons/ and the stub was never seen. The whole
# point of this fixture is which commons/ is in play, so the entry point has to
# be a real file inside it. base.inc.php:67 is where startInit() is called
# from, which is the line under test either way.
boot() {
    php -r '$_GET["node"]="schema"; require getenv("FOG_TEST_BOOT");' 2>&1
}
export FOG_TEST_BOOT="$tmp/web/commons/base.inc.php"

# 1. No config.class.php at all -- a hand-copied tree, or configureHttpd() that
#    did not finish. The failure must NAME the file. Before this change it said
#    "Class \"Config\" not found", which sends you looking for a missing class
#    rather than a missing install step.
rm -f "$tmp/web/commons/config.class.php"
out=$(boot)
grep -q 'config\.class\.php is missing or unreadable' <<<"$out"
check "a missing config.class.php is reported by name" $?
grep -q 'Class "Config" not found' <<<"$out"
check "and NOT as a missing class" $((1 - $?))

# 2. With the file present, the boot must get PAST `new Config()`. The stub
#    declares the class and nothing else, so the next thing to fail is the
#    database -- which is the proof: reaching PDODB means Config resolved.
printf '<?php\nclass Config { public function __construct() {} }\n' \
    > "$tmp/web/commons/config.class.php"
out=$(boot)
grep -q 'Class "Config" not found' <<<"$out"
check "with the file present, Config resolves" $((1 - $?))
grep -q 'config\.class\.php is missing or unreadable' <<<"$out"
check "and the not-configured guard does not misfire" $((1 - $?))

if [[ $fails -gt 0 ]]; then
    echo "FAIL ($fails of $checks)" >&2
    exit 1
fi
echo "ok  $checks checks passed"
exit 0
