<?php
/**
 * Gate: Initiator::language() leaves the message domain emitting UTF-8.
 *
 * GH-1720. Every page declares charset=UTF-8 and every catalog under
 * management/languages/ is UTF-8, but that is not what decides the bytes
 * gettext hands back. glibc converts a translation from the catalog's own
 * charset to the codeset of the ACTIVE LC_CTYPE, and substitutes a literal
 * `?` for anything the target cannot represent. language() set only
 * LC_MESSAGES, so on a php-fpm pool started with LC_CTYPE=C -- whose codeset
 * is ASCII -- the correct Chinese catalog was selected and then flattened to
 * `???` on the way out. Reported on Rocky Linux 9.8 / PHP 8.0 / php-fpm.
 *
 * WHAT THIS PINS, AND WHY IN TWO HALVES
 *
 * Neither half greps init.php. `bind_textdomain_codeset` being present in the
 * source says nothing: it can name the wrong domain, run before
 * bindtextdomain() rebinds it, or sit behind a branch this locale never
 * takes. Both halves observe gettext's own state instead.
 *
 * 1. THE STATE, on PHP 8 only. bind_textdomain_codeset($domain, null) is a
 *    pure query -- it returns the codeset in force and sets nothing. That is
 *    an 8.0 capability: 7.4's binding declares the parameter `ss`, so null is
 *    coerced to an empty string and the call SETS rather than reads. Guarding
 *    on the version is therefore not tidiness, it is the difference between
 *    reading the state and destroying it. Needs nothing but ext/gettext, so
 *    it is the half that gates on a bare runner.
 *
 * 2. THE FAILURE ITSELF, end to end, where the host can select zh_CN.UTF-8.
 *    LC_CTYPE forced to C, the tracked .po compiled by msgfmt, a real lookup
 *    through Initiator::language(), and the result checked for the 3f3f3f the
 *    reporter saw. gettext cannot select a catalog for a locale the host has
 *    not generated, and a stock CI runner carries only C and en_US, so this
 *    half says out loud when it stands down rather than passing silently.
 *
 * Usage: php tests/gettext-output-is-utf8.test.php
 * Exit 0 = clean, 1 = at least one failure.
 */

$root = dirname(__DIR__);
$fails = [];

if (!function_exists('bind_textdomain_codeset')) {
    fwrite(STDERR, "ext/gettext is not loaded; FOG cannot translate without it\n");
    exit(1);
}

/*
 * Booting the autoloader is enough to reach language() -- Initiator's
 * constructor only registers it, and language() is a pure static that touches
 * no database. FOG_CACHE_DIR and friends are redirected into a throwaway
 * directory first; see the long note in tests/autoload.test.php for why that
 * line must never become conditional.
 */
$tmp = sys_get_temp_dir() . '/fog-gettext-test-' . getmypid();
@mkdir($tmp . '/cache', 0700, true);
@mkdir($tmp . '/log', 0700, true);
register_shutdown_function(
    function () use ($tmp) {
        foreach (glob($tmp . '/*/*') ?: [] as $f) {
            @unlink($f);
        }
        foreach (glob($tmp . '/*') ?: [] as $d) {
            @rmdir($d);
        }
        @rmdir($tmp);
    }
);
define('FOG_CACHE_DIR', $tmp . '/cache');
define('FOG_LOG_DIR', $tmp . '/log');
define('FOG_PLUGIN_DIR', $tmp . '/plugins');

require_once $root . '/packages/web/commons/init.php';

$langs = ['de', 'en', 'es', 'eu', 'fr', 'it', 'pt', 'zh', 'ja'];

/*
 * 1. Every language FOG offers leaves the domain bound to UTF-8.
 *
 * All of them, not just zh: the conversion is lossy for any msgstr outside
 * the target codeset, so German umlauts and French accents are damaged by the
 * same mechanism -- less visibly, one `?` at a time.
 */
if (PHP_VERSION_ID >= 80000) {
    foreach ($langs as $lang) {
        // Bind the domain somewhere harmless and poison the codeset first. A
        // codeset set by an earlier iteration survives, so without this the
        // whole loop would pass on the strength of one call.
        bindtextdomain('messages', $tmp);
        bind_textdomain_codeset('messages', 'ISO-8859-1');

        Initiator::language($lang);

        $codeset = bind_textdomain_codeset('messages', null);
        if ('UTF-8' !== $codeset) {
            $fails[] = sprintf(
                "language('%s') left the messages domain emitting %s; every"
                . ' translation carrying a non-ASCII character is damaged on'
                . ' the way out',
                $lang,
                (false === $codeset ? 'the LC_CTYPE codeset' : (string)$codeset)
            );
        }
    }
}

/*
 * 2. The reported failure itself.
 *
 * language() resolves its catalog directory from its own __DIR__, so the
 * catalog is compiled into the real tree and whatever was there is handed
 * back afterward. The .mo files are generated by the installer and
 * gitignored, so it is built from the tracked .po by msgfmt -- the same
 * program lib/common/functions.sh uses -- not hand-assembled from an idea of
 * the format.
 */
$langdir = $root . '/packages/web/management/languages/zh_CN.UTF-8/LC_MESSAGES';
$po = $langdir . '/messages.po';
$mo = $langdir . '/messages.mo';
$msgfmt = trim((string)shell_exec('command -v msgfmt 2>/dev/null'));
$restore = setlocale(LC_MESSAGES, '0');
$selectable = false !== setlocale(LC_MESSAGES, 'zh_CN.UTF-8');
setlocale(LC_MESSAGES, (string)$restore);

if ('' === $msgfmt || !$selectable || !is_readable($po) || !is_writable($langdir)) {
    fwrite(
        STDERR,
        "note: the end-to-end half stood down (msgfmt "
        . ('' === $msgfmt ? 'missing' : 'present') . ', zh_CN.UTF-8 '
        . ($selectable ? 'selectable' : 'not generated on this host')
        . ")\n"
    );
} else {
    // A developer box has a compiled catalog here already, put there by the
    // installer. Hand it back byte for byte; this test does not own it.
    $saved = is_file($mo) ? file_get_contents($mo) : null;
    register_shutdown_function(
        function () use ($mo, $saved) {
            if (false === $saved || null === $saved) {
                @unlink($mo);
                return;
            }
            file_put_contents($mo, $saved);
        }
    );

    $out = [];
    $status = 1;
    exec(
        escapeshellarg($msgfmt) . ' -o ' . escapeshellarg($mo) . ' '
        . escapeshellarg($po) . ' 2>&1',
        $out,
        $status
    );

    if (0 !== $status || !is_file($mo)) {
        $fails[] = 'msgfmt could not compile the tracked zh_CN catalog at '
            . $po . ' (' . implode(' ', $out) . '); the shipped translation'
            . ' would not build either';
    } else {
        // C is what a php-fpm pool inherits when nothing sets a locale, and it
        // is the condition the bug needs. LC_MESSAGES is left to language() --
        // setting it here would hide a regression in the line that selects the
        // catalog.
        $wasCtype = setlocale(LC_CTYPE, '0');
        setlocale(LC_CTYPE, 'C');

        Initiator::language('zh');
        $msg = gettext('Dashboard');

        setlocale(LC_CTYPE, (string)$wasCtype);

        if ('Dashboard' === $msg) {
            $fails[] = 'the zh_CN catalog no longer translates "Dashboard";'
                . ' pick a msgid it does translate, or this check is inert';
        } elseif (false !== strpos($msg, '?')) {
            $fails[] = sprintf(
                'under LC_CTYPE=C the zh_CN translation of "Dashboard" came'
                . ' back as %s (%s) -- gettext is still converting output to'
                . ' the LC_CTYPE codeset, which is the GH-1720 failure',
                $msg,
                bin2hex($msg)
            );
        } elseif (!preg_match('//u', $msg)) {
            $fails[] = 'the zh_CN translation of "Dashboard" is not valid'
                . ' UTF-8: ' . bin2hex($msg);
        }
    }
}

if ($fails) {
    fwrite(STDERR, "FAIL\n  " . implode("\n  ", $fails) . "\n");
    exit(1);
}

echo "OK\n";
exit(0);
