<?php
/**
 * Checked-in schema DDL must not name a server-version-specific collation.
 *
 * commons/schema-expected.php is generated by bin/schema-manifest.php from
 * `SHOW CREATE TABLE` against whatever database the maintainer happened to
 * run it on, and SchemaReconciler::plan() hands those `create` strings
 * straight to the server on any install missing the table. So a collation
 * that only the GENERATING server understands ships as DDL that every other
 * server must execute -- and cannot.
 *
 * That is not hypothetical. MariaDB 11.4 changed the DEFAULT collation for
 * the Unicode charsets to the UCA-14.0.0 family, so a table created there
 * without an explicit COLLATE gets utf8mb3_uca1400_ai_ci and SHOW CREATE
 * TABLE prints it back explicitly. Regenerating the manifest on an 11.4 box
 * therefore baked utf8mb3_uca1400_ai_ci into the thirteen newest tables
 * (roles, sites and the grant/member tables) while the fifty-four older ones
 * kept utf8mb3_general_ci. On any server below 11.4 -- and on every version
 * of MySQL, which has never had these collations -- the reconciler's CREATE
 * TABLE died with:
 *
 *     1273 Unknown collation: 'utf8mb3_uca1400_ai_ci'
 *
 * The damage was not confined to the missing tables. A failed reconcile
 * leaves $errors non-empty in SchemaUpdaterPage::update(), which throws
 * before $newSchema->save(), so the schema version is never recorded. The
 * install then reports itself out of date on every subsequent request, and
 * DatabaseManager::establish() 308-redirects everything not on its four-entry
 * $okayFiles allowlist to ?node=schema. maintenance/backup_db.php is not on
 * that list, so the installer's pre-upgrade database dump was answered with a
 * redirect and an empty body -- surfacing only as "Backing up database...
 * Failed" with nothing in any log, because a 308 is not an error to either
 * Apache or curl.
 *
 * WHAT IS CHECKED, and why an allowlist. The failure mode is "a collation
 * this server knows and another one does not", which cannot be enumerated as
 * a denylist -- uca1400 is merely the family that bit us, and the next
 * MariaDB default change would ship a different name past the same gate. The
 * legitimate vocabulary of these two files is tiny (general_ci and bin), so
 * naming what is allowed is both shorter and complete. Adding a collation
 * here is a deliberate act that should be argued for in review, which is the
 * point.
 *
 * Textual, not by execution, for the same reason as schema-gate.test.php:
 * commons/schema.php calls self::$DB->query() at file scope and cannot be
 * included without a database.
 *
 * Usage: php tests/schema-portable-collation.test.php
 * Exit status 0 = pass, 1 = fail.
 */

$root = dirname(__DIR__) . '/packages/web';
$files = [
    $root . '/commons/schema.php',
    $root . '/commons/schema-expected.php',
];

/*
 * Collations available on every server FOG supports (MySQL 5.7+, MariaDB
 * 10.2+). utf8, utf8mb3 and their _general_ci collations are the same things
 * under two spellings -- utf8 was renamed utf8mb3 -- so both are listed.
 */
$portable = [
    'utf8_general_ci',
    'utf8mb3_general_ci',
    'utf8mb4_general_ci',
    'utf8_bin',
    'utf8mb3_bin',
    'utf8mb4_bin',
];

$offenders = [];
foreach ($files as $path) {
    if (!is_readable($path)) {
        fwrite(STDERR, "FAIL: cannot read $path\n");
        exit(1);
    }
    $lines = preg_split('/\r?\n/', file_get_contents($path));
    foreach ($lines as $i => $line) {
        // Both spellings the files actually use: the table-level
        // `COLLATE=x` that SHOW CREATE TABLE emits, and the column-level
        // `COLLATE x` written by hand in schema.php.
        if (!preg_match_all('/COLLATE\s*=?\s*([a-z0-9_]+)/i', $line, $m)) {
            continue;
        }
        foreach ($m[1] as $collation) {
            if (in_array(strtolower($collation), $portable, true)) {
                continue;
            }
            $offenders[] = sprintf(
                '%s:%d: %s',
                str_replace(dirname(__DIR__) . '/', '', $path),
                $i + 1,
                $collation
            );
        }
    }
}

if (count($offenders)) {
    fwrite(
        STDERR,
        'FAIL: ' . count($offenders) . " non-portable collation(s) in"
        . " checked-in schema DDL:\n"
        . '  ' . implode("\n  ", $offenders) . "\n\n"
        . "  SchemaReconciler::plan() executes these CREATE TABLE strings on\n"
        . "  any install missing the table, so a collation the generating\n"
        . "  server knew and the target does not fails the whole reconcile --\n"
        . "  which also stops the schema version being recorded, leaving every\n"
        . "  request 308-redirected to ?node=schema.\n\n"
        . "  Use utf8mb3_general_ci (or utf8_general_ci, the same collation),\n"
        . "  matching the rest of the file. If you regenerated the manifest\n"
        . "  with bin/schema-manifest.php on MariaDB 11.4+, that is where\n"
        . "  uca1400 names come from -- the generator normalizes them, so\n"
        . "  regenerate rather than hand-editing them back in.\n"
    );
    exit(1);
}

echo 'ok  no non-portable collations in ' . count($files) . " schema file(s)\n";
exit(0);
