<?php
declare(strict_types=1);

/**
 * Initiator and FOG Autoloader
 *
 * Establishes the FOG GUI and system autoloader functionality while ensuring
 * input sanitization and system initialization for performance and security.
 *
 * @category Initiator
 * @package  FOGProject
 * @author   Tom Elliott <tommygunsster@gmail.com>
 * @license  http://opensource.org/licenses/gpl-3.0 GPLv3
 * @link     https://fogproject.org
 */

/*
 * Composer's PSR-4 loader for FOG\ => packages/web/src.
 *
 * Here, at file scope, because this is the one file every entry point
 * reaches: the web UI, the API, the 41 fog-client endpoints under service/,
 * status/, maintenance/, and all nine CLI daemons via
 * packages/service/lib/service_lib.php all arrive through
 * commons/base.inc.php -> require 'init.php'. There is no second bootstrap
 * to keep in step.
 *
 * Loading here also fixes the chain order for free. spl_autoload_register is
 * a queue, and this runs at include time while Initiator::autoload() is
 * registered later inside the constructor -- so a real namespaced class in
 * src/ is found by Composer first, and only a miss falls through to the
 * short-name bridge below. That is the right precedence: the bridge is a
 * compatibility shim, not the destination.
 *
 * Guarded because the file legitimately may not be there: a checkout that
 * has not run `composer install`, and -- the case that actually matters --
 * every server installed before this commit, whose web tree has no vendor/
 * until the next upgrade re-lays it. FOG must boot without it.
 */
$fogComposerAutoload = __DIR__ . DIRECTORY_SEPARATOR . '..'
    . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
if (is_readable($fogComposerAutoload)) {
    require_once $fogComposerAutoload;
}
unset($fogComposerAutoload);

class Initiator
{
    private static $sanitizeItems;

    private static function setSanitize(): void
    {
        if (!self::$sanitizeItems) {
            self::$sanitizeItems = function (&$val, $key): void {
                if (is_array($val)) {
                    array_walk($val, self::$sanitizeItems);
                    return;
                }

                if (is_string($val)) {
                    $val = trim(str_replace("\0", '', $val));
                }
            };
        }
    }

    /**
     * No native `mixed` type hint here on purpose. `mixed` is a real type only
     * from PHP 8.0; on 7.4 the parser reads it as a *class* name, so every call
     * throws an uncaught TypeError ("must be an instance of mixed") and the
     * request dies with a zero-byte 500 before any output. _verCheck() below
     * still admits 7.4, so that is a supported target. The (string) cast makes
     * the hint redundant anyway. Refs forums.fogproject.org topic 18204.
     */
    public static function e($value): string
    {
        return htmlspecialchars(
            (string)($value ?? ''),
            ENT_QUOTES | ENT_SUBSTITUTE,
            'UTF-8',
            false
        );
    }

    public function __construct()
    {
        // Use cookies only, no URL-based sessions
        ini_set('session.use_only_cookies', '1');
        ini_set('session.use_strict_mode', '1');

        // 'secure' is intentionally false so the same session cookie is valid
        // over both HTTP and HTTPS. If you want HTTPS-only, set this to true
        // and add a hard HTTP→HTTPS redirect at the web-server level so the
        // PHP session path is never reached over plain HTTP.
        session_set_cookie_params([
            'lifetime' => 0,
            'path'     => '/',
            'domain'   => '',            // default current host
            'secure'   => false,         // false = dual HTTP+HTTPS support
            'httponly' => true,
            'samesite' => 'Lax',
        ]);

        self::setSanitize();
        define('DS', DIRECTORY_SEPARATOR);
        define('BASEPATH', self::_determineBasePath());

        // The boot file-list cache (classFileList) needs the cache dir before
        // System.class.php loads. Define the constants here, guarded, so System
        // (the canonical, documented home for FOG_BASE_DIR) defers to these.
        //
        // GH-850: fogpaths.php is generated by the installer from its
        // $fogprogramdir, so a non-default base path reaches PHP instead of
        // being assumed. It is a bare define-only file precisely so it can be
        // pulled in here -- before the autoloader exists. Absent on a pre-850
        // install or a hand-copied web tree, in which case the /opt/fog
        // fallback below keeps the previous behaviour.
        $fogPaths = __DIR__ . DS . 'fogpaths.php';
        if (is_readable($fogPaths)) {
            require_once $fogPaths;
        }
        if (!defined('FOG_BASE_DIR')) {
            define('FOG_BASE_DIR', '/opt/fog');
        }
        if (!defined('FOG_CACHE_DIR')) {
            define('FOG_CACHE_DIR', FOG_BASE_DIR . DS . 'cache');
        }
        // Fallback for the service log path. The configured value comes from
        // the SERVICE_LOG_PATH globalSetting; this is what the daemons and the
        // log viewer use when that is empty, and it mirrors the installer's
        // $servicelogs default.
        if (!defined('FOG_LOG_DIR')) {
            define('FOG_LOG_DIR', FOG_BASE_DIR . DS . 'log');
        }
        // The EXTERNAL plugin root (ADR 0009). Bundled plugins ship in the web
        // tree at BASEPATH/lib/plugins and are re-laid from the tarball on every
        // upgrade; third-party plugins live here instead, because
        // configureHttpd() does `rm -rf $webdirdest` and would delete anything
        // an admin had added. Living under FOG_BASE_DIR means it survives that
        // wipe BY CONSTRUCTION, the same property $customizationsDir relies on,
        // rather than by a backup-and-restore step that has to be re-made
        // correctly every upgrade.
        //
        // Absent on an install that has never used one; every consumer treats a
        // missing directory as "no external plugins" rather than an error.
        //
        // The final path segment MUST stay "plugins". FOGBase::fileitems()
        // decides whether a source file belongs to a plugin by looking for a
        // literal DS."plugins".DS in its path, which is how an external
        // plugin's hooks, pages and reports get picked up by the same
        // machinery as a bundled one. Point this somewhere not ending in
        // /plugins and those files are silently treated as core, which
        // bypasses the installed-plugin filter entirely.
        if (!defined('FOG_PLUGIN_DIR')) {
            define('FOG_PLUGIN_DIR', FOG_BASE_DIR . DS . 'plugins');
        }

        $allpaths = array_unique(array_map('dirname', self::classFileList()));
        set_include_path(implode(PATH_SEPARATOR, $allpaths) . PATH_SEPARATOR . get_include_path());
        spl_autoload_extensions('.class.php,.page.php,.event.php,.hook.php,.report.php,.task.php');
        // Fast path: an O(1) class-name => file map (see self::autoload). The
        // built-in autoloader is kept registered behind it as a fallback so any
        // class not yet in the (TTL-cached) map still resolves by include_path
        // probe exactly as before.
        spl_autoload_register([self::class, 'autoload']);
        spl_autoload_register();

        // Last in the chain on purpose -- see the method.
        self::_registerPluginAutoloaders();

        /*
         * Start a session only when there is one to resume or something has
         * asked for one.
         *
         * This used to be unconditional, and 62 entry points reach it through
         * commons/base.inc.php -- including every file under service/ and
         * status/, the API and the iPXE endpoints. None of those can carry a
         * cookie back, so each request allocated a session that was written
         * once, never read again, and left for gc to clean up. A PXE boot or
         * a fleet of fog-clients polling on a timer is a steady stream of
         * them.
         *
         * Browser flows are unaffected: the login page GET declares
         * FOG_WANTS_SESSION and creates the session, and every request after
         * that presents the cookie, so the first arm matches. The API accepts
         * a session cookie when a browser sends one and falls back to token
         * auth when it does not -- both still work, because the cookie is
         * exactly the signal being tested.
         *
         * Safe because nothing on the browser-less paths uses session state:
         * there is not one $_SESSION write under service/, status/, lib/
         * reg-task, lib/client or lib/service, and setMessage() already
         * returns early when no session is active (fogbase.class.php).
         */
        $hasSession = isset($_COOKIE[session_name()]);
        if (session_status() !== PHP_SESSION_ACTIVE
            && ($hasSession || defined('FOG_WANTS_SESSION'))
        ) {
            session_start();
        }
    }

    public static function language(string $lang = 'en'): void
    {
        $validLangs = ['de' => 'DE', 'en' => 'US', 'es' => 'ES', 'eu' => 'ES', 'fr' => 'FR', 'it' => 'IT', 'pt' => 'BR', 'zh' => 'CN', 'ja' => 'JP'];
        $lang = array_key_exists($lang, $validLangs) ? $lang : 'en';
        if (session_status() === PHP_SESSION_ACTIVE) {
            $_SESSION['FOG_LANG'] = $lang;
        }
        $lang = "{$lang}_{$validLangs[$lang]}";
        $domain = 'messages';
        $apppath = realpath(__DIR__ . '/../management/languages');
        setlocale(LC_MESSAGES, $lang . ".UTF-8");
        bindtextdomain($domain, $apppath);
        textdomain($domain);
    }

    private static function _determineBasePath(): string
    {
        return dirname(__DIR__) . DS;
    }

    /** Seconds a persisted file-list cache is trusted before it is rebuilt. */
    private const FILELIST_TTL = 300;

    /**
     * The one namespace prefix the bridge in autoload() answers for.
     *
     * Deliberately a constant and not a setting. A bridge whose namespace
     * varies per install is a bridge nobody can write documentation for, and
     * one that answered for ANY prefix would make a plugin's `Vendor\Host`
     * silently resolve to core's `Host`.
     */
    private const BRIDGE_NS = 'FOG\\';

    /** In-process memo of the class-source file list. */
    private static ?array $fileList = null;

    /** In-process map of lowercased class name => absolute source path. */
    private static ?array $classMap = null;

    /**
     * Every autoloadable source file under BASEPATH (*.class.php, *.page.php,
     * *.event.php, *.hook.php, *.report.php, *.task.php).
     *
     * The recursive directory walk this requires is the most expensive part of
     * each request's bootstrap (it stats the whole tree) and was previously run
     * up to three times per request (here plus each HookManager/EventManager
     * scan). It is now done once: memoised for the request and persisted to a
     * short-lived JSON cache so sibling requests skip the walk entirely. The
     * cache self-heals — rebuilt whenever it is missing, older than
     * FILELIST_TTL, or fails validation — so newly deployed classes appear
     * within the TTL with no manual flush.
     *
     * @return string[] Absolute file paths.
     */
    public static function classFileList(): array
    {
        if (self::$fileList !== null) {
            return self::$fileList;
        }
        // Keyed on every scanned root, not just BASEPATH: an install that
        // gains or loses the external plugin root has a genuinely different
        // file list, and keying on BASEPATH alone would serve it the stale one
        // until the TTL expired.
        $cacheFile = FOG_CACHE_DIR . DS . 'filelist.'
            . md5(implode('|', self::_scanRoots())) . '.json';
        $cached = self::_readFileListCache($cacheFile);
        if ($cached !== null) {
            return self::$fileList = $cached;
        }
        $files = self::_scanClassFiles();
        self::_writeFileListCache($cacheFile, $files);
        return self::$fileList = $files;
    }

    /**
     * Drops the cached class-file list so the next request rescans.
     *
     * Called when code is added to or removed from a scanned root while the
     * server is running -- which only the plugin uploader does. Without it the
     * new plugin stays invisible to the autoloader until the TTL expires: its
     * manager, page and hook classes do not resolve, so installing it applies
     * no schema, registers no hooks and renders no page, while reporting
     * success. Up to five minutes of a plugin that is "installed" and inert.
     *
     * Only the current roots' entry is removed, and a failed unlink is not an
     * error: the TTL still expires on its own, so the worst case is the delay
     * this exists to avoid.
     *
     * @return void
     */
    public static function forgetClassFileList(): void
    {
        self::$fileList = null;
        self::$classMap = null;
        @unlink(
            FOG_CACHE_DIR . DS . 'filelist.'
            . md5(implode('|', self::_scanRoots())) . '.json'
        );
    }

    /**
     * Is this path plugin code rather than core code?
     *
     * Two roots count: BASEPATH/lib/plugins, where the bundled plugins are
     * unpacked by bin/fetch-plugins.sh, and FOG_PLUGIN_DIR, where an admin's
     * own plugins live (ADR 0009). Everything else under BASEPATH is core.
     *
     * Used only to break a name collision in autoload(), so it answers the
     * one question that matters there -- may this file shadow a core class --
     * and nothing else.
     *
     * @param string $path An absolute path from the class-file scan.
     *
     * @return bool
     */
    private static function _isPluginPath(string $path): bool
    {
        $roots = [rtrim(BASEPATH, DS) . DS . 'lib' . DS . 'plugins' . DS];
        if (defined('FOG_PLUGIN_DIR') && FOG_PLUGIN_DIR) {
            $roots[] = rtrim(FOG_PLUGIN_DIR, DS) . DS;
        }
        foreach ($roots as $root) {
            if (strncmp($path, $root, strlen($root)) === 0) {
                return true;
            }
        }
        return false;
    }

    /**
     * Let a plugin ship its own Composer dependencies.
     *
     * ADR 0009 left this out, and the Phase 2 plan first read that absence as
     * "plugins cannot use Composer". They can: an autoloader is an
     * spl_autoload_register callback and several coexist in one process, so a
     * plugin could always have required its own vendor/autoload.php from a
     * file body FOG already includes. What was missing is core doing it in a
     * defined order, with a defined answer when two of them disagree.
     *
     * Registered LAST, after core's Composer loader (file scope, above),
     * Initiator::autoload() and the built-in resolver. That ordering is the
     * real protection: even if the collision check below were wrong, core
     * still answers first for any name it can serve, so a plugin's vendor
     * copy cannot displace a class core provides.
     *
     * The collision check is what makes shipping a dependency in core mean
     * something. Two plugins vendoring different majors of one package both
     * declare the same class names, and whichever registered first wins --
     * the other then runs against a version it was never tested against, with
     * nothing said. For a JWT library that is a security bug rather than an
     * inconvenience, which is why core ships firebase/php-jwt and a plugin is
     * expected to depend on it instead of carrying its own.
     *
     * A refused plugin is unregistered, not fatal: the rest of FOG, and the
     * plugin's own PHP, keep working. Only its vendored classes stop
     * resolving, which is the visible failure the silent version-skew was not.
     *
     * Caveat worth knowing: Composer's `files` autoload runs at require time,
     * so a refused plugin may already have executed those before we could
     * unregister it. Preventing that would mean parsing the vendor tree
     * instead of loading it, which buys less than it costs.
     *
     * @return void
     */
    private static function _registerPluginAutoloaders(): void
    {
        if (!class_exists('\Composer\Autoload\ClassLoader', false)) {
            // No core vendor/ -- an install predating Phase 0, or a checkout
            // that never ran composer install. Nothing to register against.
            return;
        }
        $claimed = [];
        foreach (self::_composerLoaders() as $loader) {
            foreach (self::_claimsOf($loader) as $claim) {
                $claimed[$claim] = 'FOG core';
            }
        }
        foreach (self::_pluginVendorAutoloads() as $plugin => $file) {
            $loader = require $file;
            if (!$loader instanceof \Composer\Autoload\ClassLoader) {
                error_log(
                    sprintf(
                        'FOG plugin autoloader: %s did not return a Composer '
                        . 'ClassLoader. Regenerate it with `composer install`.',
                        $file
                    )
                );
                continue;
            }
            $claims = self::_claimsOf($loader);
            $conflicts = array_intersect($claims, array_keys($claimed));
            if (count($conflicts) > 0) {
                $loader->unregister();
                $first = reset($conflicts);
                error_log(
                    sprintf(
                        'FOG plugin autoloader: refusing %s -- it vendors %s, '
                        . 'already provided by %s (%d name(s) in common). Two '
                        . 'copies of one package resolve to whichever loaded '
                        . 'first, silently. Depend on the provided copy, or '
                        . 'raise it with the FOG project if core should ship '
                        . 'a different version.',
                        $file,
                        preg_replace('#^(ns|class):#', '', (string) $first),
                        $claimed[$first],
                        count($conflicts)
                    )
                );
                continue;
            }
            foreach ($claims as $claim) {
                $claimed[$claim] = $plugin;
            }
        }
    }

    /**
     * Every Composer ClassLoader currently in the autoload chain.
     *
     * Read out of spl_autoload_functions() rather than tracked in a property,
     * so it sees core's loader however it got there -- including on a tree
     * where something else required vendor/autoload.php first.
     *
     * @return \Composer\Autoload\ClassLoader[]
     */
    private static function _composerLoaders(): array
    {
        $loaders = [];
        foreach ((array) spl_autoload_functions() as $fn) {
            if (is_array($fn)
                && isset($fn[0])
                && $fn[0] instanceof \Composer\Autoload\ClassLoader
            ) {
                $loaders[] = $fn[0];
            }
        }
        return $loaders;
    }

    /**
     * The class names a loader claims, as comparable strings.
     *
     * Namespace prefixes and classmap entries both, because a package can be
     * autoloaded either way -- PSR-4 for the normal case, a classmap for one
     * that predates it. `optimize-autoloader` adds a classmap without
     * dropping the prefixes, so an optimised tree is caught by either.
     *
     * @param \Composer\Autoload\ClassLoader $loader The loader to inspect.
     *
     * @return string[]
     */
    private static function _claimsOf($loader): array
    {
        $claims = [];
        foreach (array_keys($loader->getPrefixesPsr4()) as $ns) {
            $claims[] = 'ns:' . strtolower($ns);
        }
        foreach (array_keys($loader->getPrefixes()) as $ns) {
            $claims[] = 'ns:' . strtolower($ns);
        }
        foreach (array_keys($loader->getClassMap()) as $class) {
            $claims[] = 'class:' . strtolower($class);
        }
        return array_values(array_unique($claims));
    }

    /**
     * Plugin name => its vendor/autoload.php, for every plugin that has one.
     *
     * Both plugin roots, one level deep: a plugin is a directory, its
     * dependencies are vendor/ inside it. Sorted so the order two plugins are
     * offered in is a property of their names rather than of readdir -- the
     * same per-install nondeterminism the class map had before core-wins.
     *
     * @return array<string,string>
     */
    private static function _pluginVendorAutoloads(): array
    {
        $found = [];
        $roots = [rtrim(BASEPATH, DS) . DS . 'lib' . DS . 'plugins'];
        if (defined('FOG_PLUGIN_DIR') && FOG_PLUGIN_DIR) {
            $roots[] = rtrim(FOG_PLUGIN_DIR, DS);
        }
        foreach ($roots as $root) {
            if (!is_dir($root)) {
                continue;
            }
            foreach ((array) scandir($root) as $entry) {
                if ('.' === $entry || '..' === $entry) {
                    continue;
                }
                $file = $root . DS . $entry . DS . 'vendor' . DS . 'autoload.php';
                if (is_readable($file)) {
                    $found[$entry] = $file;
                }
            }
        }
        ksort($found);
        return $found;
    }

    /**
     * Resolve a class to its source file via an O(1) name => path map.
     *
     * The built-in spl_autoload() probes every include_path directory by every
     * registered extension on each class load — tens of thousands of failed
     * stat() calls per request. This replaces that with a single hash lookup.
     *
     * The map is derived once per request from classFileList() (itself memoised
     * and TTL-cached), keyed on the lowercased basename minus its .<type>.php
     * suffix — exactly what the built-in resolver matches. A miss falls through
     * to the still-registered built-in autoloader.
     *
     * Where two files claim one key, CORE WINS and the collision is logged.
     * Keeping colliding basenames out of the scan is still the rule (see
     * _scanClassFiles) -- this is what happens when that rule is broken.
     *
     * It used to be "first one walked wins", which is readdir order and so
     * differs per install: the same code resolving to a different file on two
     * servers, silently. That is the usertracking failure documented in
     * _scanClassFiles, and it had a second edge nobody had cause to look at
     * yet -- external plugins under FOG_PLUGIN_DIR already lost to core,
     * because _scanRoots() puts BASEPATH first and first-wins does the rest,
     * but BUNDLED plugins live *inside* BASEPATH at lib/plugins, so they
     * shared one directory walk with lib/fog and the winner was a coin flip.
     * A bundled plugin shipping class/authorization.class.php could therefore
     * replace core's Authorization on some installs and not others.
     *
     * Core winning makes the two plugin roots behave the same way, which is
     * the behaviour the external-plugin case already had, and it is the only
     * safe direction: a plugin must never be able to shadow a core class by
     * naming a file after it. Verified against the shipped tree at the time
     * of writing -- 396 scanned files, zero colliding basenames -- so this
     * changes no resolution that exists today.
     *
     * Note this is still NOT what the built-in does: spl_autoload() loops the
     * registered extensions on the outside and the include_path on the inside,
     * so a .class.php always beats a .report.php of the same name however the
     * directories are ordered. Two core files colliding remain unordered, and
     * are reported rather than resolved.
     *
     * A name that misses the map and carries the FOG\ prefix falls through to
     * _bridgeNamespaced() below rather than to the built-in resolver, which
     * cannot find it -- see that method.
     *
     * @param string $class The class being autoloaded.
     *
     * @return void
     */
    public static function autoload(string $class): void
    {
        if (self::$classMap === null) {
            $map = [];
            foreach (self::classFileList() as $path) {
                $base = strtolower(
                    preg_replace(
                        '#\.(report|event|class|hook|page|task)\.php$#',
                        '',
                        basename($path)
                    )
                );
                if (!isset($map[$base])) {
                    $map[$base] = $path;
                    continue;
                }
                // Collision. Let a core file displace a plugin one, and say so
                // either way -- a shadowed class is otherwise completely
                // silent, and the symptom (a method that does not exist, or
                // one that reads the wrong table) surfaces nowhere near here.
                $held = $map[$base];
                if (self::_isPluginPath($held) && !self::_isPluginPath($path)) {
                    $map[$base] = $path;
                }
                $loser = ($map[$base] === $held) ? $path : $held;
                error_log(
                    sprintf(
                        'FOG autoloader: two files claim the class name "%s"; '
                        . 'using %s and ignoring %s. Rename one -- a shadowed '
                        . 'class resolves to whichever file this rule picks, '
                        . 'not to the one the caller meant.',
                        $base,
                        $map[$base],
                        $loser
                    )
                );
            }
            self::$classMap = $map;
        }
        $key = strtolower($class);
        if (isset(self::$classMap[$key])) {
            // include_once, not include. PHP does not call an autoloader
            // twice for a name it managed to declare -- but it calls it every
            // time for one it did not, and a file whose declared class name
            // does not match its filename never satisfies the lookup. The
            // second class_exists() on such a name re-included the file and
            // died on "Cannot declare class X, because the name is already in
            // use": an uncatchable fatal, so a bodyless HTTP 500. Proven with
            // a plugin shipping class/<name>manager.class.php declaring
            // something else.
            include_once self::$classMap[$key];
            return;
        }

        self::_bridgeNamespaced($class);
    }

    /**
     * Resolve a FOG\<Name> request to the still-global <Name> and alias it.
     *
     * Nothing in the tree is namespaced yet, so `FOG\User` currently misses
     * everywhere and does so silently. autoload()'s map is keyed on a
     * lowercased basename, and no basename can contain a backslash, so
     * `fog\user` is never a key; the bare spl_autoload() registered behind it
     * then converts the separator to a directory and probes for
     * `fog/user.class.php`, which no include_path entry holds. No error, no
     * log line, just a class-not-found at the call site.
     *
     * This makes the namespaced spelling work ahead of the files themselves
     * moving, so call sites and plugin code can be written forward-compatibly
     * now and the eventual migration is not also a flag day for every caller.
     * class_alias produces one class entry under two names, so `instanceof`,
     * `new`, Reflection and every getClass() consumer see a single type.
     * (get_class() still reports the DECLARED name -- that asymmetry is why
     * namespacing the models is a separate problem from bridging their names,
     * and why this is safe while that is not.)
     *
     * Flat names only. A nested request such as FOG\Model\Host is the shape
     * the real migration will use, and answering it here by guessing at the
     * last segment would resolve two different future classes to one file.
     *
     * @param string $class The namespaced class being autoloaded.
     *
     * @return void
     */
    private static function _bridgeNamespaced(string $class): void
    {
        if (strncasecmp($class, self::BRIDGE_NS, strlen(self::BRIDGE_NS)) !== 0) {
            return;
        }
        $short = substr($class, strlen(self::BRIDGE_NS));
        if ($short === '' || strpos($short, '\\') !== false) {
            return;
        }
        $key = strtolower($short);
        if (!isset(self::$classMap[$key])) {
            return;
        }
        include_once self::$classMap[$key];
        // Phase 3: the file may declare the namespaced name ITSELF, and then
        // alias the global one back the other way. There is nothing left to
        // bridge in that case, and aliasing again would be a "Cannot declare
        // class FOG\X, because the name is already in use" warning on every
        // single class load. Checked before the branch below, because that
        // branch's own condition is satisfied too -- the file's own
        // class_alias() has by now declared the short name.
        if (class_exists($class, false)
            || interface_exists($class, false)
            || trait_exists($class, false)
        ) {
            return;
        }
        // Checked with autoload OFF. With it on, a file whose declared class
        // name does not match its basename would re-enter autoload() for the
        // same short name and hit the "Cannot declare class X" fatal the
        // include_once above exists to avoid. Aliasing a name that was never
        // declared is itself a fatal, so both halves matter: only alias what
        // the include actually produced, and let PHP raise its own
        // catchable class-not-found for anything else.
        if (class_exists($short, false)
            || interface_exists($short, false)
            || trait_exists($short, false)
        ) {
            class_alias($short, $class);
        }
    }

    /**
     * The roots the class scan walks: the web tree, plus the external plugin
     * root when it exists.
     *
     * Both are returned with a trailing separator so a prefix comparison
     * cannot match a sibling directory whose name merely starts the same way
     * ("/opt/fog/plugins" must not accept "/opt/fog/plugins-backup").
     *
     * @return string[]
     */
    private static function _scanRoots(): array
    {
        $roots = [rtrim(BASEPATH, DS) . DS];
        if (is_dir(FOG_PLUGIN_DIR)) {
            $roots[] = rtrim(FOG_PLUGIN_DIR, DS) . DS;
        }
        return $roots;
    }

    private static function _scanClassFiles(): array
    {
        $regext = '#^.*\.(report|event|class|hook|page|task)\.php$#';
        // Walked directly rather than through a symlink from the web tree.
        // Activation does symlink an external plugin into lib/plugins so the
        // browser can fetch its js/css, but RecursiveDirectoryIterator does
        // NOT descend into a symlinked directory -- it yields the link itself
        // as one entry -- so the link is invisible here. That is deliberate:
        // scanning the real path finds each file exactly once, with no
        // FOLLOW_SYMLINKS flag that would make the walk chase every other
        // symlink in the tree as well.
        $matches = [];
        foreach (self::_scanRoots() as $root) {
            $matches = array_merge(
                $matches,
                iterator_to_array(
                    new \RegexIterator(
                        new \RecursiveIteratorIterator(
                            new \RecursiveDirectoryIterator(
                                $root,
                                \FilesystemIterator::SKIP_DOTS
                            )
                        ),
                        $regext,
                        \RegexIterator::GET_MATCH
                    ),
                    false
                )
            );
        }
        // service/ holds fog-client entry points, not class sources, and one of
        // them -- usertracking.report.php -- matches the *.report.php pattern.
        // Its map key ("usertracking") collides with lib/fog/usertracking.class
        // .php, and on a collision the file the directory walk reached first
        // wins: readdir order, so identical code fails on one install and not
        // the next. Where the entry point won, autoloading UserTracking -- which
        // only the Login History grid does -- executed it, and its
        // `require '../commons/base.inc.php'` booted FOG a second time:
        // "Cannot declare class Initiator", a bodyless 500 on that one table.
        // Nothing under service/ declares a class, so drop the directory rather
        // than special-case the one file.
        //
        // vendor/ is dropped for a related reason. Composer packages are
        // PSR-4 and use bare .php, so today none of them matches $regext at
        // all -- but "today" is the whole problem: a dependency that ships
        // one file called anything.class.php would silently claim that map
        // key, and third-party code winning a name collision against a FOG
        // class is not a failure mode worth leaving open for the sake of two
        // lines. Composer's own autoloader resolves everything under vendor/;
        // this scan must never be a second route to it.
        $entryPoints = BASEPATH . 'service' . DS;
        $vendor = BASEPATH . 'vendor' . DS;
        return array_values(
            array_filter(
                array_column($matches, 0),
                function ($path) use ($entryPoints, $vendor) {
                    return strncmp($path, $entryPoints, strlen($entryPoints)) !== 0
                        && strncmp($path, $vendor, strlen($vendor)) !== 0;
                }
            )
        );
    }

    private static function _readFileListCache(string $file): ?array
    {
        clearstatcache(true, $file);
        if (!is_file($file)
            || (time() - (int) filemtime($file)) > self::FILELIST_TTL
        ) {
            return null;
        }
        $json = @file_get_contents($file);
        if ($json === false) {
            return null;
        }
        $data = json_decode($json, true);
        if (!is_array($data) || $data === []) {
            return null;
        }
        // FOG_CACHE_DIR is world-writable (sticky). Reject any list pointing
        // outside the scanned roots so a poisoned cache can never feed foreign
        // paths to the autoloader; in-root-but-stale is healed by the TTL.
        //
        // The external plugin root is a second accepted prefix, not a hole:
        // it is only accepted while it exists, and the roots carry a trailing
        // separator so a prefix match cannot escape into a sibling directory.
        // Note this makes write access to FOG_PLUGIN_DIR equivalent to write
        // access to the code tree -- which it already is, since the autoloader
        // loads what lives there.
        //
        // The UI plugin installer (ADR 0009 tier 3) deliberately makes that
        // directory web-writable, so on a server that has turned it on this
        // guard no longer separates "the web user can write it" from "the
        // autoloader will load it". That is the accepted cost of the feature,
        // not an oversight, and it is why turning it on takes two acts: the
        // FOG_PLUGIN_UI_INSTALL_ENABLED setting AND a root-run
        // bin/fog-plugin-uploads.sh. The guard still earns its keep --
        // FOG_CACHE_DIR itself is world-writable and is never a scan root, so
        // a poisoned list still cannot point the autoloader at the cache.
        $roots = self::_scanRoots();
        foreach ($data as $path) {
            if (!is_string($path)) {
                return null;
            }
            $inRoot = false;
            foreach ($roots as $root) {
                if (strncmp($path, $root, strlen($root)) === 0) {
                    $inRoot = true;
                    break;
                }
            }
            if (!$inRoot) {
                return null;
            }
        }
        return $data;
    }

    private static function _writeFileListCache(string $file, array $files): void
    {
        $json = json_encode(array_values($files));
        if ($json === false) {
            return;
        }
        $tmp = $file . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, $json, LOCK_EX) === false) {
            return;
        }
        @chmod($tmp, 0600);
        if (!@rename($tmp, $file)) {
            @unlink($tmp);
        }
    }

    public static function startInit(): void
    {
        error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);
        new self;
        self::sanitizeItems();
        self::_verCheck();
        self::_extCheck();
        $globalVars = ['newService', 'json', 'node', 'sub', 'printertype', 'id', 'groupid', 'crit', 'sort', 'confirm', 'tab', 'type'];
        foreach ($globalVars as $var) {
            global $$var;
            $$var = filter_input(INPUT_GET, $var) ?? filter_input(INPUT_POST, $var);
        }
        new System();
        new Config();
        self::language($_SESSION['FOG_LANG'] ?? 'en');
    }

    public static function sanitizeItems(&$value = '')
    {
        self::setSanitize();
        $process = [&$_GET, &$_POST, &$_COOKIE, &$_SESSION];
        array_walk($process, self::$sanitizeItems);
        return $value;
    }

    private static function _verCheck(): void
    {
        if (version_compare(phpversion(), '7.4', '<')) {
            throw new \Exception('FOG Requires PHP v7.4 or higher. You have PHP v' . phpversion());
        }
    }

    private static function _extCheck(): void
    {
        $requiredExtensions = ['gettext', 'mysqli'];
        $loadedExtensions = get_loaded_extensions();
        if (count(array_intersect($requiredExtensions, $loadedExtensions)) < count($requiredExtensions)) {
            throw new \Exception(_('Missing one or more extensions.'));
        }
    }

    public static function sanitizeOutput(string $buffer): string
    {
        $search = ['/>\s+</', '/(\s)+/'];
        $replace = ['> <', '\\1'];
        return preg_replace($search, $replace, $buffer) ?? $buffer;
    }
}
