<?php
declare(strict_types=1);

/**
 * Initiator and FOG Autoloader
 *
 * Establishes the FOG GUI and system autoloader functionality while ensuring
 * input sanitization and system initialization for performance and security.
 *
 * @category Initiator
 * @package  FOGProject
 * @author   Tom Elliott <tommygunsster@gmail.com>
 * @license  http://opensource.org/licenses/gpl-3.0 GPLv3
 * @link     https://fogproject.org
 */
class Initiator
{
    private static $sanitizeItems;

    private static function setSanitize(): void
    {
        if (!self::$sanitizeItems) {
            self::$sanitizeItems = function (&$val, $key): void {
                if (is_array($val)) {
                    array_walk($val, self::$sanitizeItems);
                    return;
                }

                if (is_string($val)) {
                    $val = trim(str_replace("\0", '', $val));
                }
            };
        }
    }

    /**
     * No native `mixed` type hint here on purpose. `mixed` is a real type only
     * from PHP 8.0; on 7.4 the parser reads it as a *class* name, so every call
     * throws an uncaught TypeError ("must be an instance of mixed") and the
     * request dies with a zero-byte 500 before any output. _verCheck() below
     * still admits 7.4, so that is a supported target. The (string) cast makes
     * the hint redundant anyway. Refs forums.fogproject.org topic 18204.
     */
    public static function e($value): string
    {
        return htmlspecialchars(
            (string)($value ?? ''),
            ENT_QUOTES | ENT_SUBSTITUTE,
            'UTF-8',
            false
        );
    }

    public function __construct()
    {
        // Use cookies only, no URL-based sessions
        ini_set('session.use_only_cookies', '1');
        ini_set('session.use_strict_mode', '1');

        // 'secure' is intentionally false so the same session cookie is valid
        // over both HTTP and HTTPS. If you want HTTPS-only, set this to true
        // and add a hard HTTP→HTTPS redirect at the web-server level so the
        // PHP session path is never reached over plain HTTP.
        session_set_cookie_params([
            'lifetime' => 0,
            'path'     => '/',
            'domain'   => '',            // default current host
            'secure'   => false,         // false = dual HTTP+HTTPS support
            'httponly' => true,
            'samesite' => 'Lax',
        ]);

        self::setSanitize();
        define('DS', DIRECTORY_SEPARATOR);
        define('BASEPATH', self::_determineBasePath());

        // The boot file-list cache (classFileList) needs the cache dir before
        // System.class.php loads. Define the constants here, guarded, so System
        // (the canonical, documented home for FOG_BASE_DIR) defers to these.
        //
        // GH-850: fogpaths.php is generated by the installer from its
        // $fogprogramdir, so a non-default base path reaches PHP instead of
        // being assumed. It is a bare define-only file precisely so it can be
        // pulled in here -- before the autoloader exists. Absent on a pre-850
        // install or a hand-copied web tree, in which case the /opt/fog
        // fallback below keeps the previous behaviour.
        $fogPaths = __DIR__ . DS . 'fogpaths.php';
        if (is_readable($fogPaths)) {
            require_once $fogPaths;
        }
        if (!defined('FOG_BASE_DIR')) {
            define('FOG_BASE_DIR', '/opt/fog');
        }
        if (!defined('FOG_CACHE_DIR')) {
            define('FOG_CACHE_DIR', FOG_BASE_DIR . DS . 'cache');
        }
        // Fallback for the service log path. The configured value comes from
        // the SERVICE_LOG_PATH globalSetting; this is what the daemons and the
        // log viewer use when that is empty, and it mirrors the installer's
        // $servicelogs default.
        if (!defined('FOG_LOG_DIR')) {
            define('FOG_LOG_DIR', FOG_BASE_DIR . DS . 'log');
        }
        // The EXTERNAL plugin root (ADR 0009). Bundled plugins ship in the web
        // tree at BASEPATH/lib/plugins and are re-laid from the tarball on every
        // upgrade; third-party plugins live here instead, because
        // configureHttpd() does `rm -rf $webdirdest` and would delete anything
        // an admin had added. Living under FOG_BASE_DIR means it survives that
        // wipe BY CONSTRUCTION, the same property $customizationsDir relies on,
        // rather than by a backup-and-restore step that has to be re-made
        // correctly every upgrade.
        //
        // Absent on an install that has never used one; every consumer treats a
        // missing directory as "no external plugins" rather than an error.
        //
        // The final path segment MUST stay "plugins". FOGBase::fileitems()
        // decides whether a source file belongs to a plugin by looking for a
        // literal DS."plugins".DS in its path, which is how an external
        // plugin's hooks, pages and reports get picked up by the same
        // machinery as a bundled one. Point this somewhere not ending in
        // /plugins and those files are silently treated as core, which
        // bypasses the installed-plugin filter entirely.
        if (!defined('FOG_PLUGIN_DIR')) {
            define('FOG_PLUGIN_DIR', FOG_BASE_DIR . DS . 'plugins');
        }

        $allpaths = array_unique(array_map('dirname', self::classFileList()));
        set_include_path(implode(PATH_SEPARATOR, $allpaths) . PATH_SEPARATOR . get_include_path());
        spl_autoload_extensions('.class.php,.page.php,.event.php,.hook.php,.report.php');
        // Fast path: an O(1) class-name => file map (see self::autoload). The
        // built-in autoloader is kept registered behind it as a fallback so any
        // class not yet in the (TTL-cached) map still resolves by include_path
        // probe exactly as before.
        spl_autoload_register([self::class, 'autoload']);
        spl_autoload_register();

        if (session_status() !== PHP_SESSION_ACTIVE) {
            session_start();
        }
    }

    public static function language(string $lang = 'en'): void
    {
        $validLangs = ['de' => 'DE', 'en' => 'US', 'es' => 'ES', 'eu' => 'ES', 'fr' => 'FR', 'it' => 'IT', 'pt' => 'BR', 'zh' => 'CN', 'ja' => 'JP'];
        $lang = array_key_exists($lang, $validLangs) ? $lang : 'en';
        if (session_status() === PHP_SESSION_ACTIVE) {
            $_SESSION['FOG_LANG'] = $lang;
        }
        $lang = "{$lang}_{$validLangs[$lang]}";
        $domain = 'messages';
        $apppath = realpath(__DIR__ . '/../management/languages');
        setlocale(LC_MESSAGES, $lang . ".UTF-8");
        bindtextdomain($domain, $apppath);
        textdomain($domain);
    }

    private static function _determineBasePath(): string
    {
        return dirname(__DIR__) . DS;
    }

    /** Seconds a persisted file-list cache is trusted before it is rebuilt. */
    private const FILELIST_TTL = 300;

    /** In-process memo of the class-source file list. */
    private static ?array $fileList = null;

    /** In-process map of lowercased class name => absolute source path. */
    private static ?array $classMap = null;

    /**
     * Every autoloadable source file under BASEPATH (*.class.php, *.page.php,
     * *.event.php, *.hook.php, *.report.php).
     *
     * The recursive directory walk this requires is the most expensive part of
     * each request's bootstrap (it stats the whole tree) and was previously run
     * up to three times per request (here plus each HookManager/EventManager
     * scan). It is now done once: memoised for the request and persisted to a
     * short-lived JSON cache so sibling requests skip the walk entirely. The
     * cache self-heals — rebuilt whenever it is missing, older than
     * FILELIST_TTL, or fails validation — so newly deployed classes appear
     * within the TTL with no manual flush.
     *
     * @return string[] Absolute file paths.
     */
    public static function classFileList(): array
    {
        if (self::$fileList !== null) {
            return self::$fileList;
        }
        // Keyed on every scanned root, not just BASEPATH: an install that
        // gains or loses the external plugin root has a genuinely different
        // file list, and keying on BASEPATH alone would serve it the stale one
        // until the TTL expired.
        $cacheFile = FOG_CACHE_DIR . DS . 'filelist.'
            . md5(implode('|', self::_scanRoots())) . '.json';
        $cached = self::_readFileListCache($cacheFile);
        if ($cached !== null) {
            return self::$fileList = $cached;
        }
        $files = self::_scanClassFiles();
        self::_writeFileListCache($cacheFile, $files);
        return self::$fileList = $files;
    }

    /**
     * Resolve a class to its source file via an O(1) name => path map.
     *
     * The built-in spl_autoload() probes every include_path directory by every
     * registered extension on each class load — tens of thousands of failed
     * stat() calls per request. This replaces that with a single hash lookup.
     *
     * The map is derived once per request from classFileList() (itself memoised
     * and TTL-cached), keyed on the lowercased basename minus its .<type>.php
     * suffix — exactly what the built-in resolver matches. A miss falls through
     * to the still-registered built-in autoloader.
     *
     * Where two files claim one key the first one walked wins, and that is NOT
     * what the built-in does: spl_autoload() loops the registered extensions on
     * the outside and the include_path on the inside, so a .class.php always
     * beats a .report.php of the same name however the directories are ordered.
     * This map has no such precedence — the winner is readdir order, which
     * differs per install. Keep colliding basenames out of the scan (see
     * _scanClassFiles) rather than relying on either rule.
     *
     * @param string $class The class being autoloaded.
     *
     * @return void
     */
    public static function autoload(string $class): void
    {
        if (self::$classMap === null) {
            $map = [];
            foreach (self::classFileList() as $path) {
                $base = strtolower(
                    preg_replace(
                        '#\.(report|event|class|hook|page)\.php$#',
                        '',
                        basename($path)
                    )
                );
                if (!isset($map[$base])) {
                    $map[$base] = $path;
                }
            }
            self::$classMap = $map;
        }
        $key = strtolower($class);
        if (isset(self::$classMap[$key])) {
            include self::$classMap[$key];
        }
    }

    /**
     * The roots the class scan walks: the web tree, plus the external plugin
     * root when it exists.
     *
     * Both are returned with a trailing separator so a prefix comparison
     * cannot match a sibling directory whose name merely starts the same way
     * ("/opt/fog/plugins" must not accept "/opt/fog/plugins-backup").
     *
     * @return string[]
     */
    private static function _scanRoots(): array
    {
        $roots = [rtrim(BASEPATH, DS) . DS];
        if (is_dir(FOG_PLUGIN_DIR)) {
            $roots[] = rtrim(FOG_PLUGIN_DIR, DS) . DS;
        }
        return $roots;
    }

    private static function _scanClassFiles(): array
    {
        $regext = '#^.*\.(report|event|class|hook|page)\.php$#';
        // Walked directly rather than through a symlink from the web tree.
        // Activation does symlink an external plugin into lib/plugins so the
        // browser can fetch its js/css, but RecursiveDirectoryIterator does
        // NOT descend into a symlinked directory -- it yields the link itself
        // as one entry -- so the link is invisible here. That is deliberate:
        // scanning the real path finds each file exactly once, with no
        // FOLLOW_SYMLINKS flag that would make the walk chase every other
        // symlink in the tree as well.
        $matches = [];
        foreach (self::_scanRoots() as $root) {
            $matches = array_merge(
                $matches,
                iterator_to_array(
                    new RegexIterator(
                        new RecursiveIteratorIterator(
                            new RecursiveDirectoryIterator(
                                $root,
                                FileSystemIterator::SKIP_DOTS
                            )
                        ),
                        $regext,
                        RegexIterator::GET_MATCH
                    ),
                    false
                )
            );
        }
        // service/ holds fog-client entry points, not class sources, and one of
        // them -- usertracking.report.php -- matches the *.report.php pattern.
        // Its map key ("usertracking") collides with lib/fog/usertracking.class
        // .php, and on a collision the file the directory walk reached first
        // wins: readdir order, so identical code fails on one install and not
        // the next. Where the entry point won, autoloading UserTracking -- which
        // only the Login History grid does -- executed it, and its
        // `require '../commons/base.inc.php'` booted FOG a second time:
        // "Cannot declare class Initiator", a bodyless 500 on that one table.
        // Nothing under service/ declares a class, so drop the directory rather
        // than special-case the one file.
        $entryPoints = BASEPATH . 'service' . DS;
        return array_values(
            array_filter(
                array_column($matches, 0),
                function ($path) use ($entryPoints) {
                    return strncmp($path, $entryPoints, strlen($entryPoints)) !== 0;
                }
            )
        );
    }

    private static function _readFileListCache(string $file): ?array
    {
        clearstatcache(true, $file);
        if (!is_file($file)
            || (time() - (int) filemtime($file)) > self::FILELIST_TTL
        ) {
            return null;
        }
        $json = @file_get_contents($file);
        if ($json === false) {
            return null;
        }
        $data = json_decode($json, true);
        if (!is_array($data) || $data === []) {
            return null;
        }
        // FOG_CACHE_DIR is world-writable (sticky). Reject any list pointing
        // outside the scanned roots so a poisoned cache can never feed foreign
        // paths to the autoloader; in-root-but-stale is healed by the TTL.
        //
        // The external plugin root is a second accepted prefix, not a hole:
        // it is only accepted while it exists, and the roots carry a trailing
        // separator so a prefix match cannot escape into a sibling directory.
        // Note this makes write access to FOG_PLUGIN_DIR equivalent to write
        // access to the code tree -- which it already is, since the autoloader
        // loads what lives there.
        //
        // The UI plugin installer (ADR 0009 tier 3) deliberately makes that
        // directory web-writable, so on a server that has turned it on this
        // guard no longer separates "the web user can write it" from "the
        // autoloader will load it". That is the accepted cost of the feature,
        // not an oversight, and it is why turning it on takes two acts: the
        // FOG_PLUGIN_UI_INSTALL_ENABLED setting AND a root-run
        // bin/fog-plugin-uploads.sh. The guard still earns its keep --
        // FOG_CACHE_DIR itself is world-writable and is never a scan root, so
        // a poisoned list still cannot point the autoloader at the cache.
        $roots = self::_scanRoots();
        foreach ($data as $path) {
            if (!is_string($path)) {
                return null;
            }
            $inRoot = false;
            foreach ($roots as $root) {
                if (strncmp($path, $root, strlen($root)) === 0) {
                    $inRoot = true;
                    break;
                }
            }
            if (!$inRoot) {
                return null;
            }
        }
        return $data;
    }

    private static function _writeFileListCache(string $file, array $files): void
    {
        $json = json_encode(array_values($files));
        if ($json === false) {
            return;
        }
        $tmp = $file . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, $json, LOCK_EX) === false) {
            return;
        }
        @chmod($tmp, 0600);
        if (!@rename($tmp, $file)) {
            @unlink($tmp);
        }
    }

    public static function startInit(): void
    {
        error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);
        new self;
        self::sanitizeItems();
        self::_verCheck();
        self::_extCheck();
        $globalVars = ['newService', 'json', 'node', 'sub', 'printertype', 'id', 'groupid', 'crit', 'sort', 'confirm', 'tab', 'type'];
        foreach ($globalVars as $var) {
            global $$var;
            $$var = filter_input(INPUT_GET, $var) ?? filter_input(INPUT_POST, $var);
        }
        new System();
        new Config();
        self::language($_SESSION['FOG_LANG'] ?? 'en');
    }

    public static function sanitizeItems(&$value = '')
    {
        self::setSanitize();
        $process = [&$_GET, &$_POST, &$_COOKIE, &$_SESSION];
        array_walk($process, self::$sanitizeItems);
        return $value;
    }

    private static function _verCheck(): void
    {
        if (version_compare(phpversion(), '7.4', '<')) {
            throw new Exception('FOG Requires PHP v7.4 or higher. You have PHP v' . phpversion());
        }
    }

    private static function _extCheck(): void
    {
        $requiredExtensions = ['gettext', 'mysqli'];
        $loadedExtensions = get_loaded_extensions();
        if (count(array_intersect($requiredExtensions, $loadedExtensions)) < count($requiredExtensions)) {
            throw new Exception(_('Missing one or more extensions.'));
        }
    }

    public static function sanitizeOutput(string $buffer): string
    {
        $search = ['/>\s+</', '/(\s)+/'];
        $replace = ['> <', '\\1'];
        return preg_replace($search, $replace, $buffer) ?? $buffer;
    }
}
