<?php
/**
 * Expected database structure for this release.
 *
 * GENERATED FILE -- do not hand-edit the `tables` block. Regenerate
 * with:  php bin/schema-manifest.php generate <fog-web-root>
 *
 * The `renames` block IS maintained by hand and is preserved across
 * regeneration. A manifest describes an END state, so a renamed
 * column is indistinguishable from a new one; without an entry here
 * SchemaReconciler would add the target column empty and strand the
 * data in the old one.
 *
 * Consumed by SchemaReconciler::reconcile().
 *
 * PHP version 7.4+
 *
 * @category SchemaExpected
 * @package  FOGProject
 * @author   Tom Elliott <tommygunsster\@gmail.com>
 * @license  http://opensource.org/licenses/gpl-3.0 GPLv3
 * @link     https://fogproject.org
 */
return [
    'renames' => [
        [
            'table' => 'plugins',
            'from' => 'pAnon1',
            'to' => 'pIcon',
            'type' => 'LONGTEXT NOT NULL',
        ],
        [
            'table' => 'plugins',
            'from' => 'pAnon2',
            'to' => 'pRunfile',
            'type' => 'LONGTEXT NOT NULL',
        ],
        [
            'table' => 'plugins',
            'from' => 'pAnon3',
            'to' => 'pLocation',
            'type' => 'LONGTEXT NOT NULL',
        ],
        [
            'table' => 'plugins',
            'from' => 'pAnon4',
            'to' => 'pDescription',
            'type' => 'LONGTEXT NOT NULL',
        ],
        [
            'table' => 'multicastSessions',
            'from' => 'msAnon3',
            'to' => 'msShutdown',
            'type' => 'ENUM(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
        ],
        [
            'table' => 'multicastSessions',
            'from' => 'msAnon4',
            'to' => 'msMaxwait',
            'type' => 'INT(11) NOT NULL',
        ],
    ],
    'tables' => [
        'clientUpdates' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `clientUpdates` ( `cuID` int(11) NOT NULL AUTO_INCREMENT, `cuName` varchar(200) NOT NULL, `cuMD5` varchar(100) NOT NULL, `cuType` varchar(30) NOT NULL, `cuFile` longblob NOT NULL, PRIMARY KEY (`cuID`), KEY `new_index` (`cuName`), KEY `new_index1` (`cuType`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'cuID' => 'int(11) NOT NULL',
                'cuName' => 'varchar(200) NOT NULL',
                'cuMD5' => 'varchar(100) NOT NULL',
                'cuType' => 'varchar(30) NOT NULL',
                'cuFile' => 'longblob NOT NULL',
            ],
        ],
        'dirCleaner' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `dirCleaner` ( `dcID` int(11) NOT NULL AUTO_INCREMENT, `dcPath` longtext NOT NULL, PRIMARY KEY (`dcID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'dcID' => 'int(11) NOT NULL',
                'dcPath' => 'longtext NOT NULL',
            ],
        ],
        'dmidecodeKeys' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `dmidecodeKeys` ( `dkID` int(11) NOT NULL AUTO_INCREMENT, `dkName` varchar(255) NOT NULL, PRIMARY KEY (`dkID`), UNIQUE KEY `name` (`dkName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'dkID' => 'int(11) NOT NULL',
                'dkName' => 'varchar(255) NOT NULL',
            ],
        ],
        'fileDeleteQueue' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `fileDeleteQueue` ( `fdqID` int(11) NOT NULL AUTO_INCREMENT, `fdqPathName` varchar(255) NOT NULL, `fdqStorageGroupID` int(11) NOT NULL, `fdqCreateDate` datetime DEFAULT current_timestamp(), `fdqCompletedDate` datetime DEFAULT NULL, `fdqCreateBy` varchar(40) DEFAULT NULL, `fdqState` int(11) NOT NULL, `fdqPathType` varchar(255) NOT NULL, PRIMARY KEY (`fdqID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'fdqID' => 'int(11) NOT NULL',
                'fdqPathName' => 'varchar(255) NOT NULL',
                'fdqStorageGroupID' => 'int(11) NOT NULL',
                'fdqCreateDate' => 'datetime DEFAULT current_timestamp()',
                'fdqCompletedDate' => 'datetime DEFAULT NULL',
                'fdqCreateBy' => 'varchar(40) DEFAULT NULL',
                'fdqState' => 'int(11) NOT NULL',
                'fdqPathType' => 'varchar(255) NOT NULL',
            ],
        ],
        'globalSettings' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `globalSettings` ( `settingID` int(11) NOT NULL AUTO_INCREMENT, `settingKey` varchar(255) NOT NULL, `settingDesc` longtext NOT NULL, `settingValue` longtext NOT NULL, `settingCategory` longtext NOT NULL, PRIMARY KEY (`settingID`), UNIQUE KEY `settingKey` (`settingKey`), UNIQUE KEY `settingKey_2` (`settingKey`), UNIQUE KEY `settingKey_3` (`settingKey`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'settingID' => 'int(11) NOT NULL',
                'settingKey' => 'varchar(255) NOT NULL',
                'settingDesc' => 'longtext NOT NULL',
                'settingValue' => 'longtext NOT NULL',
                'settingCategory' => 'longtext NOT NULL',
            ],
        ],
        'greenFog' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `greenFog` ( `gfID` int(11) NOT NULL AUTO_INCREMENT, `gfHostID` int(11) NOT NULL, `gfHour` int(11) NOT NULL, `gfMin` int(11) NOT NULL, `gfAction` varchar(2) NOT NULL, `gfDays` varchar(25) NOT NULL, PRIMARY KEY (`gfID`), KEY `new_index` (`gfHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'gfID' => 'int(11) NOT NULL',
                'gfHostID' => 'int(11) NOT NULL',
                'gfHour' => 'int(11) NOT NULL',
                'gfMin' => 'int(11) NOT NULL',
                'gfAction' => 'varchar(2) NOT NULL',
                'gfDays' => 'varchar(25) NOT NULL',
            ],
        ],
        'groupMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `groupMembers` ( `gmID` int(11) NOT NULL AUTO_INCREMENT, `gmHostID` int(11) NOT NULL, `gmGroupID` int(11) NOT NULL, PRIMARY KEY (`gmID`), UNIQUE KEY `gmHostID` (`gmHostID`,`gmGroupID`), UNIQUE KEY `gmGroupID` (`gmHostID`,`gmGroupID`), KEY `new_index` (`gmHostID`), KEY `new_index1` (`gmGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'gmID' => 'int(11) NOT NULL',
                'gmHostID' => 'int(11) NOT NULL',
                'gmGroupID' => 'int(11) NOT NULL',
            ],
        ],
        'groups' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `groups` ( `groupID` int(11) NOT NULL AUTO_INCREMENT, `groupName` varchar(50) NOT NULL, `groupDesc` longtext NOT NULL, `groupDateTime` timestamp NOT NULL DEFAULT current_timestamp(), `groupCreateBy` varchar(50) NOT NULL, `groupBuilding` int(11) NOT NULL, `groupKernel` varchar(255) NOT NULL, `groupKernelArgs` varchar(255) NOT NULL, `groupPrimaryDisk` varchar(255) NOT NULL, `groupInit` longtext NOT NULL, PRIMARY KEY (`groupID`), UNIQUE KEY `groupName` (`groupName`), UNIQUE KEY `groupName_2` (`groupName`), KEY `new_index` (`groupName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'groupID' => 'int(11) NOT NULL',
                'groupName' => 'varchar(50) NOT NULL',
                'groupDesc' => 'longtext NOT NULL',
                'groupDateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'groupCreateBy' => 'varchar(50) NOT NULL',
                'groupBuilding' => 'int(11) NOT NULL',
                'groupKernel' => 'varchar(255) NOT NULL',
                'groupKernelArgs' => 'varchar(255) NOT NULL',
                'groupPrimaryDisk' => 'varchar(255) NOT NULL',
                'groupInit' => 'longtext NOT NULL',
            ],
        ],
        'history' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `history` ( `hID` int(11) NOT NULL AUTO_INCREMENT, `hText` varchar(255) NOT NULL, `hUser` varchar(200) NOT NULL, `hTime` timestamp NOT NULL DEFAULT current_timestamp(), `hIP` varchar(50) NOT NULL, PRIMARY KEY (`hID`), UNIQUE KEY `updateTime` (`hText`,`hTime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'hID' => 'int(11) NOT NULL',
                'hText' => 'varchar(255) NOT NULL',
                'hUser' => 'varchar(200) NOT NULL',
                'hTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'hIP' => 'varchar(50) NOT NULL',
            ],
        ],
        'hookEvents' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `hookEvents` ( `heID` int(11) NOT NULL AUTO_INCREMENT, `heName` varchar(255) NOT NULL, PRIMARY KEY (`heID`), UNIQUE KEY `name` (`heName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'heID' => 'int(11) NOT NULL',
                'heName' => 'varchar(255) NOT NULL',
            ],
        ],
        'hostAutoLogOut' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `hostAutoLogOut` ( `haloID` int(11) NOT NULL AUTO_INCREMENT, `haloHostID` int(11) NOT NULL, `haloTime` varchar(10) NOT NULL, PRIMARY KEY (`haloID`), UNIQUE KEY `haloHostID` (`haloHostID`), KEY `new_index` (`haloHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'haloID' => 'int(11) NOT NULL',
                'haloHostID' => 'int(11) NOT NULL',
                'haloTime' => 'varchar(10) NOT NULL',
            ],
        ],
        'hostMAC' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `hostMAC` ( `hmID` int(11) NOT NULL AUTO_INCREMENT, `hmHostID` int(11) NOT NULL, `hmMAC` varchar(59) NOT NULL, `hmDesc` longtext NOT NULL, `hmPrimary` enum(\'0\',\'1\') NOT NULL, `hmPending` enum(\'0\',\'1\') NOT NULL, `hmIgnoreClient` enum(\'0\',\'1\') NOT NULL, `hmIgnoreImaging` enum(\'0\',\'1\') NOT NULL, PRIMARY KEY (`hmID`), UNIQUE KEY `hmHostID` (`hmMAC`), UNIQUE KEY `hmMAC` (`hmMAC`), UNIQUE KEY `hmMAC_2` (`hmMAC`), KEY `idxHostID` (`hmHostID`), KEY `idxMac` (`hmMAC`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'hmID' => 'int(11) NOT NULL',
                'hmHostID' => 'int(11) NOT NULL',
                'hmMAC' => 'varchar(59) NOT NULL',
                'hmDesc' => 'longtext NOT NULL',
                'hmPrimary' => 'enum(\'0\',\'1\') NOT NULL',
                'hmPending' => 'enum(\'0\',\'1\') NOT NULL',
                'hmIgnoreClient' => 'enum(\'0\',\'1\') NOT NULL',
                'hmIgnoreImaging' => 'enum(\'0\',\'1\') NOT NULL',
            ],
        ],
        'hosts' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `hosts` ( `hostID` int(11) NOT NULL AUTO_INCREMENT, `hostName` varchar(16) NOT NULL, `hostDesc` longtext NOT NULL, `hostIP` varchar(25) NOT NULL, `hostImage` int(11) NOT NULL, `hostBuilding` int(11) NOT NULL, `hostCreateDate` timestamp NOT NULL DEFAULT current_timestamp(), `hostLastDeploy` datetime NOT NULL, `hostCreateBy` varchar(50) NOT NULL, `hostUseAD` char(1) NOT NULL, `hostADDomain` varchar(250) NOT NULL, `hostADOU` longtext NOT NULL, `hostADUser` varchar(250) NOT NULL, `hostADPass` varchar(250) NOT NULL, `hostADPassLegacy` longtext NOT NULL, `hostProductKey` longtext DEFAULT NULL, `hostPrinterLevel` varchar(2) NOT NULL, `hostKernelArgs` varchar(250) NOT NULL, `hostKernel` varchar(250) NOT NULL, `hostDevice` varchar(250) NOT NULL, `hostInit` longtext DEFAULT NULL, `hostPending` enum(\'0\',\'1\') NOT NULL, `hostPubKey` longtext NOT NULL, `hostSecToken` longtext NOT NULL, `hostSecTime` timestamp NOT NULL, `hostPingCode` varchar(20) DEFAULT NULL, `hostExitBios` longtext DEFAULT NULL, `hostExitEfi` longtext DEFAULT NULL, `hostEnforce` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `hostInfoKey` varchar(255) DEFAULT NULL, `hostInfoLock` tinyint(1) DEFAULT 0, `hostSecTokenPrev` longtext NOT NULL, PRIMARY KEY (`hostID`), UNIQUE KEY `hostName` (`hostName`), KEY `new_index` (`hostName`), KEY `new_index1` (`hostIP`), KEY `new_index4` (`hostUseAD`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'hostID' => 'int(11) NOT NULL',
                'hostName' => 'varchar(16) NOT NULL',
                'hostDesc' => 'longtext NOT NULL',
                'hostIP' => 'varchar(25) NOT NULL',
                'hostImage' => 'int(11) NOT NULL',
                'hostBuilding' => 'int(11) NOT NULL',
                'hostCreateDate' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'hostLastDeploy' => 'datetime NOT NULL',
                'hostCreateBy' => 'varchar(50) NOT NULL',
                'hostUseAD' => 'char(1) NOT NULL',
                'hostADDomain' => 'varchar(250) NOT NULL',
                'hostADOU' => 'longtext NOT NULL',
                'hostADUser' => 'varchar(250) NOT NULL',
                'hostADPass' => 'varchar(250) NOT NULL',
                'hostADPassLegacy' => 'longtext NOT NULL',
                'hostProductKey' => 'longtext DEFAULT NULL',
                'hostPrinterLevel' => 'varchar(2) NOT NULL',
                'hostKernelArgs' => 'varchar(250) NOT NULL',
                'hostKernel' => 'varchar(250) NOT NULL',
                'hostDevice' => 'varchar(250) NOT NULL',
                'hostInit' => 'longtext DEFAULT NULL',
                'hostPending' => 'enum(\'0\',\'1\') NOT NULL',
                'hostPubKey' => 'longtext NOT NULL',
                'hostSecToken' => 'longtext NOT NULL',
                'hostSecTime' => 'timestamp NOT NULL',
                'hostPingCode' => 'varchar(20) DEFAULT NULL',
                'hostExitBios' => 'longtext DEFAULT NULL',
                'hostExitEfi' => 'longtext DEFAULT NULL',
                'hostEnforce' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'hostInfoKey' => 'varchar(255) DEFAULT NULL',
                'hostInfoLock' => 'tinyint(1) DEFAULT 0',
                'hostSecTokenPrev' => 'longtext NOT NULL',
            ],
        ],
        'hostScreenSettings' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `hostScreenSettings` ( `hssID` int(11) NOT NULL AUTO_INCREMENT, `hssHostID` int(11) NOT NULL, `hssWidth` int(11) NOT NULL, `hssHeight` int(11) NOT NULL, `hssRefresh` int(11) NOT NULL, `hssOrientation` int(11) NOT NULL, `hssOther1` int(11) NOT NULL, `hssOther2` int(11) NOT NULL, PRIMARY KEY (`hssID`), UNIQUE KEY `hssHostID` (`hssHostID`), KEY `new_index` (`hssHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'hssID' => 'int(11) NOT NULL',
                'hssHostID' => 'int(11) NOT NULL',
                'hssWidth' => 'int(11) NOT NULL',
                'hssHeight' => 'int(11) NOT NULL',
                'hssRefresh' => 'int(11) NOT NULL',
                'hssOrientation' => 'int(11) NOT NULL',
                'hssOther1' => 'int(11) NOT NULL',
                'hssOther2' => 'int(11) NOT NULL',
            ],
        ],
        'imageGroupAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `imageGroupAssoc` ( `igaID` mediumint(9) NOT NULL AUTO_INCREMENT, `igaImageID` mediumint(9) NOT NULL, `igaStorageGroupID` mediumint(9) NOT NULL, `igaPrimary` enum(\'0\',\'1\') NOT NULL, PRIMARY KEY (`igaID`), UNIQUE KEY `igaImageID` (`igaImageID`,`igaStorageGroupID`), UNIQUE KEY `igaImageID_2` (`igaImageID`,`igaStorageGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'igaID' => 'mediumint(9) NOT NULL',
                'igaImageID' => 'mediumint(9) NOT NULL',
                'igaStorageGroupID' => 'mediumint(9) NOT NULL',
                'igaPrimary' => 'enum(\'0\',\'1\') NOT NULL',
            ],
        ],
        'imagePartitionTypes' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `imagePartitionTypes` ( `imagePartitionTypeID` mediumint(9) NOT NULL AUTO_INCREMENT, `imagePartitionTypeName` varchar(100) NOT NULL, `imagePartitionTypeValue` varchar(10) NOT NULL, PRIMARY KEY (`imagePartitionTypeID`), UNIQUE KEY `imagePartitionTypeName` (`imagePartitionTypeName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'imagePartitionTypeID' => 'mediumint(9) NOT NULL',
                'imagePartitionTypeName' => 'varchar(100) NOT NULL',
                'imagePartitionTypeValue' => 'varchar(10) NOT NULL',
            ],
        ],
        'images' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `images` ( `imageID` int(11) NOT NULL AUTO_INCREMENT, `imageName` varchar(40) NOT NULL, `imageDesc` longtext NOT NULL, `imagePath` longtext NOT NULL, `imageProtect` mediumint(9) NOT NULL, `imageMagnetUri` longtext NOT NULL, `imageDateTime` timestamp NOT NULL DEFAULT current_timestamp(), `imageCreateBy` varchar(50) NOT NULL, `imageBuilding` int(11) NOT NULL, `imageSize` varchar(255) NOT NULL, `imageTypeID` mediumint(9) NOT NULL, `imagePartitionTypeID` mediumint(9) NOT NULL, `imageOSID` mediumint(9) NOT NULL, `imageFormat` char(1) DEFAULT NULL, `imageLastDeploy` datetime NOT NULL, `imageCompress` int(11) DEFAULT NULL, `imageEnabled` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `imageReplicate` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `imageServerSize` bigint(20) unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`imageID`), UNIQUE KEY `imageName` (`imageName`), KEY `new_index` (`imageName`), KEY `new_index1` (`imageBuilding`), KEY `new_index2` (`imageTypeID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'imageID' => 'int(11) NOT NULL',
                'imageName' => 'varchar(40) NOT NULL',
                'imageDesc' => 'longtext NOT NULL',
                'imagePath' => 'longtext NOT NULL',
                'imageProtect' => 'mediumint(9) NOT NULL',
                'imageMagnetUri' => 'longtext NOT NULL',
                'imageDateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'imageCreateBy' => 'varchar(50) NOT NULL',
                'imageBuilding' => 'int(11) NOT NULL',
                'imageSize' => 'varchar(255) NOT NULL',
                'imageTypeID' => 'mediumint(9) NOT NULL',
                'imagePartitionTypeID' => 'mediumint(9) NOT NULL',
                'imageOSID' => 'mediumint(9) NOT NULL',
                'imageFormat' => 'char(1) DEFAULT NULL',
                'imageLastDeploy' => 'datetime NOT NULL',
                'imageCompress' => 'int(11) DEFAULT NULL',
                'imageEnabled' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'imageReplicate' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'imageServerSize' => 'bigint(20) unsigned NOT NULL DEFAULT 0',
            ],
        ],
        'imageTypes' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `imageTypes` ( `imageTypeID` mediumint(9) NOT NULL AUTO_INCREMENT, `imageTypeName` varchar(100) NOT NULL, `imageTypeValue` varchar(10) NOT NULL, PRIMARY KEY (`imageTypeID`), UNIQUE KEY `imageTypeValue` (`imageTypeValue`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'imageTypeID' => 'mediumint(9) NOT NULL',
                'imageTypeName' => 'varchar(100) NOT NULL',
                'imageTypeValue' => 'varchar(10) NOT NULL',
            ],
        ],
        'imagingLog' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `imagingLog` ( `ilID` int(11) NOT NULL AUTO_INCREMENT, `ilHostID` int(11) NOT NULL, `ilStartTime` datetime NOT NULL, `ilFinishTime` datetime NOT NULL, `ilImageName` varchar(64) NOT NULL, `ilType` varchar(64) NOT NULL, `ilCreatedBy` varchar(255) NOT NULL, PRIMARY KEY (`ilID`), KEY `new_index` (`ilHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ilID' => 'int(11) NOT NULL',
                'ilHostID' => 'int(11) NOT NULL',
                'ilStartTime' => 'datetime NOT NULL',
                'ilFinishTime' => 'datetime NOT NULL',
                'ilImageName' => 'varchar(64) NOT NULL',
                'ilType' => 'varchar(64) NOT NULL',
                'ilCreatedBy' => 'varchar(255) NOT NULL',
            ],
        ],
        'inventory' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `inventory` ( `iID` int(11) NOT NULL AUTO_INCREMENT, `iHostID` int(11) NOT NULL, `iPrimaryUser` varchar(50) NOT NULL, `iOtherTag` varchar(50) NOT NULL, `iOtherTag1` varchar(50) NOT NULL, `iCreateDate` timestamp NOT NULL DEFAULT current_timestamp(), `iDeleteDate` datetime NOT NULL, `iSysman` varchar(250) NOT NULL, `iSysproduct` varchar(250) NOT NULL, `iSysversion` varchar(250) NOT NULL, `iSysserial` varchar(250) NOT NULL, `iSystype` varchar(250) NOT NULL, `iBiosversion` varchar(250) NOT NULL, `iBiosvendor` varchar(250) NOT NULL, `iBiosdate` varchar(250) NOT NULL, `iMbman` varchar(250) NOT NULL, `iMbproductname` varchar(250) NOT NULL, `iMbversion` varchar(250) NOT NULL, `iMbserial` varchar(250) NOT NULL, `iMbasset` varchar(250) NOT NULL, `iCpuman` varchar(250) NOT NULL, `iCpuversion` varchar(250) NOT NULL, `iCpucurrent` varchar(250) NOT NULL, `iCpumax` varchar(250) NOT NULL, `iMem` varchar(250) NOT NULL, `iHdmodel` varchar(250) NOT NULL, `iHdfirmware` varchar(250) NOT NULL, `iHdserial` varchar(250) NOT NULL, `iCaseman` varchar(250) NOT NULL, `iCasever` varchar(250) NOT NULL, `iCaseserial` varchar(250) NOT NULL, `iCaseasset` varchar(250) NOT NULL, `iSystemUUID` varchar(255) NOT NULL, `iGpuvendors` varchar(255) NOT NULL, `iGpuproducts` varchar(255) NOT NULL, PRIMARY KEY (`iID`), UNIQUE KEY `iHostID_2` (`iHostID`), KEY `iHostID` (`iHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'iID' => 'int(11) NOT NULL',
                'iHostID' => 'int(11) NOT NULL',
                'iPrimaryUser' => 'varchar(50) NOT NULL',
                'iOtherTag' => 'varchar(50) NOT NULL',
                'iOtherTag1' => 'varchar(50) NOT NULL',
                'iCreateDate' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'iDeleteDate' => 'datetime NOT NULL',
                'iSysman' => 'varchar(250) NOT NULL',
                'iSysproduct' => 'varchar(250) NOT NULL',
                'iSysversion' => 'varchar(250) NOT NULL',
                'iSysserial' => 'varchar(250) NOT NULL',
                'iSystype' => 'varchar(250) NOT NULL',
                'iBiosversion' => 'varchar(250) NOT NULL',
                'iBiosvendor' => 'varchar(250) NOT NULL',
                'iBiosdate' => 'varchar(250) NOT NULL',
                'iMbman' => 'varchar(250) NOT NULL',
                'iMbproductname' => 'varchar(250) NOT NULL',
                'iMbversion' => 'varchar(250) NOT NULL',
                'iMbserial' => 'varchar(250) NOT NULL',
                'iMbasset' => 'varchar(250) NOT NULL',
                'iCpuman' => 'varchar(250) NOT NULL',
                'iCpuversion' => 'varchar(250) NOT NULL',
                'iCpucurrent' => 'varchar(250) NOT NULL',
                'iCpumax' => 'varchar(250) NOT NULL',
                'iMem' => 'varchar(250) NOT NULL',
                'iHdmodel' => 'varchar(250) NOT NULL',
                'iHdfirmware' => 'varchar(250) NOT NULL',
                'iHdserial' => 'varchar(250) NOT NULL',
                'iCaseman' => 'varchar(250) NOT NULL',
                'iCasever' => 'varchar(250) NOT NULL',
                'iCaseserial' => 'varchar(250) NOT NULL',
                'iCaseasset' => 'varchar(250) NOT NULL',
                'iSystemUUID' => 'varchar(255) NOT NULL',
                'iGpuvendors' => 'varchar(255) NOT NULL',
                'iGpuproducts' => 'varchar(255) NOT NULL',
            ],
        ],
        'ipxeTable' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `ipxeTable` ( `ipxeID` mediumint(9) NOT NULL AUTO_INCREMENT, `ipxeProduct` longtext NOT NULL, `ipxeManufacturer` longtext NOT NULL, `ipxeFilename` longtext NOT NULL, `ipxeMAC` varchar(17) NOT NULL, `ipxeSuccess` varchar(2) NOT NULL, `ipxeFailure` varchar(2) NOT NULL, `ipxeVersion` longtext NOT NULL, PRIMARY KEY (`ipxeID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ipxeID' => 'mediumint(9) NOT NULL',
                'ipxeProduct' => 'longtext NOT NULL',
                'ipxeManufacturer' => 'longtext NOT NULL',
                'ipxeFilename' => 'longtext NOT NULL',
                'ipxeMAC' => 'varchar(17) NOT NULL',
                'ipxeSuccess' => 'varchar(2) NOT NULL',
                'ipxeFailure' => 'varchar(2) NOT NULL',
                'ipxeVersion' => 'longtext NOT NULL',
            ],
        ],
        'keySequence' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `keySequence` ( `ksID` int(11) NOT NULL AUTO_INCREMENT, `ksValue` varchar(25) NOT NULL, `ksAscii` varchar(25) NOT NULL, PRIMARY KEY (`ksID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ksID' => 'int(11) NOT NULL',
                'ksValue' => 'varchar(25) NOT NULL',
                'ksAscii' => 'varchar(25) NOT NULL',
            ],
        ],
        'modules' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `modules` ( `id` mediumint(9) NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL, `short_name` varchar(30) NOT NULL, `description` text NOT NULL, `default` int(11) NOT NULL DEFAULT 1, PRIMARY KEY (`id`), UNIQUE KEY `short_name` (`short_name`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'id' => 'mediumint(9) NOT NULL',
                'name' => 'varchar(50) NOT NULL',
                'short_name' => 'varchar(30) NOT NULL',
                'description' => 'text NOT NULL',
                'default' => 'int(11) NOT NULL DEFAULT 1',
            ],
        ],
        'moduleStatusByHost' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `moduleStatusByHost` ( `msID` int(11) NOT NULL AUTO_INCREMENT, `msHostID` int(11) NOT NULL, `msModuleID` int(11) NOT NULL, `msState` varchar(1) NOT NULL, PRIMARY KEY (`msID`), UNIQUE KEY `msHostID` (`msHostID`,`msModuleID`), UNIQUE KEY `msHostID_2` (`msHostID`,`msModuleID`), KEY `new_index` (`msHostID`), KEY `new_index2` (`msModuleID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'msID' => 'int(11) NOT NULL',
                'msHostID' => 'int(11) NOT NULL',
                'msModuleID' => 'int(11) NOT NULL',
                'msState' => 'varchar(1) NOT NULL',
            ],
        ],
        'multicastSessions' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `multicastSessions` ( `msID` int(11) NOT NULL AUTO_INCREMENT, `msName` varchar(250) NOT NULL, `msBasePort` int(11) NOT NULL, `msLogPath` longtext NOT NULL, `msImage` longtext NOT NULL, `msClients` int(11) NOT NULL, `msSessClients` int(11) NOT NULL, `msInterface` varchar(250) NOT NULL, `msStartDateTime` datetime NOT NULL, `msPercent` int(11) NOT NULL, `msState` int(11) NOT NULL, `msCompleteDateTime` datetime NOT NULL, `msIsDD` int(11) NOT NULL, `msNFSGroupID` int(11) NOT NULL, `msShutdown` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `msMaxwait` int(11) NOT NULL, `msAnon5` varchar(250) NOT NULL, `msSenderPID` int(11) NOT NULL DEFAULT 0, `msSenderNode` int(11) NOT NULL DEFAULT 0, `msSenderStart` datetime DEFAULT NULL, PRIMARY KEY (`msID`), KEY `new_index` (`msNFSGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'msID' => 'int(11) NOT NULL',
                'msName' => 'varchar(250) NOT NULL',
                'msBasePort' => 'int(11) NOT NULL',
                'msLogPath' => 'longtext NOT NULL',
                'msImage' => 'longtext NOT NULL',
                'msClients' => 'int(11) NOT NULL',
                'msSessClients' => 'int(11) NOT NULL',
                'msInterface' => 'varchar(250) NOT NULL',
                'msStartDateTime' => 'datetime NOT NULL',
                'msPercent' => 'int(11) NOT NULL',
                'msState' => 'int(11) NOT NULL',
                'msCompleteDateTime' => 'datetime NOT NULL',
                'msIsDD' => 'int(11) NOT NULL',
                'msNFSGroupID' => 'int(11) NOT NULL',
                'msShutdown' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'msMaxwait' => 'int(11) NOT NULL',
                'msAnon5' => 'varchar(250) NOT NULL',
                'msSenderPID' => 'int(11) NOT NULL DEFAULT 0',
                'msSenderNode' => 'int(11) NOT NULL DEFAULT 0',
                'msSenderStart' => 'datetime DEFAULT NULL',
            ],
        ],
        'multicastSessionsAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `multicastSessionsAssoc` ( `msaID` int(11) NOT NULL AUTO_INCREMENT, `msID` int(11) NOT NULL, `tID` int(11) NOT NULL, PRIMARY KEY (`msaID`), UNIQUE KEY `msID` (`msID`,`tID`), KEY `new_index` (`msID`), KEY `new_index1` (`tID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'msaID' => 'int(11) NOT NULL',
                'msID' => 'int(11) NOT NULL',
                'tID' => 'int(11) NOT NULL',
            ],
        ],
        'nfsFailures' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `nfsFailures` ( `nfID` int(11) NOT NULL AUTO_INCREMENT, `nfNodeID` int(11) NOT NULL, `nfTaskID` int(11) NOT NULL, `nfHostID` int(11) NOT NULL, `nfGroupID` int(11) NOT NULL, `nfDateTime` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`nfID`), UNIQUE KEY `nfNodeID` (`nfNodeID`,`nfHostID`,`nfTaskID`), KEY `new_index` (`nfNodeID`), KEY `new_index1` (`nfTaskID`), KEY `new_index2` (`nfHostID`), KEY `new_index3` (`nfGroupID`), KEY `new_index4` (`nfDateTime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'nfID' => 'int(11) NOT NULL',
                'nfNodeID' => 'int(11) NOT NULL',
                'nfTaskID' => 'int(11) NOT NULL',
                'nfHostID' => 'int(11) NOT NULL',
                'nfGroupID' => 'int(11) NOT NULL',
                'nfDateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
            ],
        ],
        'nfsGroupMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `nfsGroupMembers` ( `ngmID` int(11) NOT NULL AUTO_INCREMENT, `ngmMemberName` varchar(250) NOT NULL, `ngmMemberDescription` longtext NOT NULL, `ngmIsMasterNode` char(1) NOT NULL, `ngmGroupID` int(11) NOT NULL, `ngmRootPath` longtext NOT NULL, `ngmSSLPath` longtext NOT NULL, `ngmFTPPath` longtext NOT NULL, `ngmMaxBitrate` varchar(25) DEFAULT NULL, `ngmHelloInterval` varchar(8) DEFAULT NULL, `ngmGraphColor` varchar(6) DEFAULT NULL, `ngmSnapinPath` longtext NOT NULL, `ngmIsEnabled` char(1) NOT NULL, `ngmHostname` varchar(250) NOT NULL, `ngmMaxClients` int(11) NOT NULL, `ngmBandwidthLimit` int(20) NOT NULL, `ngmUser` varchar(250) NOT NULL, `ngmPass` varchar(250) NOT NULL, `ngmKey` varchar(250) NOT NULL, `ngmInterface` varchar(25) NOT NULL DEFAULT \'\', `ngmGraphEnabled` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `ngmWebroot` longtext NOT NULL, PRIMARY KEY (`ngmID`), UNIQUE KEY `ngmMemberName` (`ngmMemberName`), UNIQUE KEY `ngmMemberName_2` (`ngmMemberName`), KEY `new_index` (`ngmMemberName`), KEY `new_index2` (`ngmIsMasterNode`), KEY `new_index3` (`ngmGroupID`), KEY `new_index4` (`ngmIsEnabled`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ngmID' => 'int(11) NOT NULL',
                'ngmMemberName' => 'varchar(250) NOT NULL',
                'ngmMemberDescription' => 'longtext NOT NULL',
                'ngmIsMasterNode' => 'char(1) NOT NULL',
                'ngmGroupID' => 'int(11) NOT NULL',
                'ngmRootPath' => 'longtext NOT NULL',
                'ngmSSLPath' => 'longtext NOT NULL',
                'ngmFTPPath' => 'longtext NOT NULL',
                'ngmMaxBitrate' => 'varchar(25) DEFAULT NULL',
                'ngmHelloInterval' => 'varchar(8) DEFAULT NULL',
                'ngmGraphColor' => 'varchar(6) DEFAULT NULL',
                'ngmSnapinPath' => 'longtext NOT NULL',
                'ngmIsEnabled' => 'char(1) NOT NULL',
                'ngmHostname' => 'varchar(250) NOT NULL',
                'ngmMaxClients' => 'int(11) NOT NULL',
                'ngmBandwidthLimit' => 'int(20) NOT NULL',
                'ngmUser' => 'varchar(250) NOT NULL',
                'ngmPass' => 'varchar(250) NOT NULL',
                'ngmKey' => 'varchar(250) NOT NULL',
                'ngmInterface' => 'varchar(25) NOT NULL DEFAULT \'\'',
                'ngmGraphEnabled' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'ngmWebroot' => 'longtext NOT NULL',
            ],
        ],
        'nfsGroups' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `nfsGroups` ( `ngID` int(11) NOT NULL AUTO_INCREMENT, `ngName` varchar(250) NOT NULL, `ngDesc` longtext NOT NULL, `ngTrustedCIDRs` varchar(2048) NOT NULL DEFAULT \'\', PRIMARY KEY (`ngID`), UNIQUE KEY `ngName` (`ngName`), UNIQUE KEY `ngName_2` (`ngName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ngID' => 'int(11) NOT NULL',
                'ngName' => 'varchar(250) NOT NULL',
                'ngDesc' => 'longtext NOT NULL',
                'ngTrustedCIDRs' => 'varchar(2048) NOT NULL DEFAULT \'\'',
            ],
        ],
        'notifyEvents' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `notifyEvents` ( `neID` int(11) NOT NULL AUTO_INCREMENT, `neName` varchar(255) NOT NULL, PRIMARY KEY (`neID`), UNIQUE KEY `name` (`neName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'neID' => 'int(11) NOT NULL',
                'neName' => 'varchar(255) NOT NULL',
            ],
        ],
        'os' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `os` ( `osID` mediumint(9) NOT NULL AUTO_INCREMENT, `osName` varchar(30) NOT NULL, `osDescription` text NOT NULL, PRIMARY KEY (`osID`), UNIQUE KEY `osName` (`osName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'osID' => 'mediumint(9) NOT NULL',
                'osName' => 'varchar(30) NOT NULL',
                'osDescription' => 'text NOT NULL',
            ],
        ],
        'oui' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `oui` ( `ouiID` int(11) NOT NULL AUTO_INCREMENT, `ouiMACPrefix` varchar(8) NOT NULL, `ouiMan` varchar(254) NOT NULL, PRIMARY KEY (`ouiID`), UNIQUE KEY `ouiMACPrefix` (`ouiMACPrefix`,`ouiMan`), KEY `idxMac` (`ouiMACPrefix`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ouiID' => 'int(11) NOT NULL',
                'ouiMACPrefix' => 'varchar(8) NOT NULL',
                'ouiMan' => 'varchar(254) NOT NULL',
            ],
        ],
        'plugins' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `plugins` ( `pID` int(11) NOT NULL AUTO_INCREMENT, `pName` varchar(100) NOT NULL, `pState` char(1) NOT NULL, `pInstalled` char(1) NOT NULL, `pVersion` varchar(100) NOT NULL, `pIcon` longtext NOT NULL, `pRunfile` longtext NOT NULL, `pLocation` longtext NOT NULL, `pDescription` longtext NOT NULL, `pAnon5` varchar(100) NOT NULL, `pSchema` int(11) NOT NULL DEFAULT 0, PRIMARY KEY (`pID`), UNIQUE KEY `pName` (`pName`), KEY `new_index` (`pName`), KEY `new_index1` (`pState`), KEY `new_index2` (`pInstalled`), KEY `new_index3` (`pVersion`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'pID' => 'int(11) NOT NULL',
                'pName' => 'varchar(100) NOT NULL',
                'pState' => 'char(1) NOT NULL',
                'pInstalled' => 'char(1) NOT NULL',
                'pVersion' => 'varchar(100) NOT NULL',
                'pIcon' => 'longtext NOT NULL',
                'pRunfile' => 'longtext NOT NULL',
                'pLocation' => 'longtext NOT NULL',
                'pDescription' => 'longtext NOT NULL',
                'pAnon5' => 'varchar(100) NOT NULL',
                'pSchema' => 'int(11) NOT NULL DEFAULT 0',
            ],
        ],
        'powerManagement' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `powerManagement` ( `pmID` int(11) NOT NULL AUTO_INCREMENT, `pmHostID` int(11) NOT NULL, `pmMin` varchar(50) NOT NULL, `pmHour` varchar(50) NOT NULL, `pmDom` varchar(50) NOT NULL, `pmMonth` varchar(50) NOT NULL, `pmDow` varchar(50) NOT NULL, `pmAction` enum(\'shutdown\',\'reboot\',\'wol\') NOT NULL, `pmOndemand` enum(\'0\',\'1\') NOT NULL, PRIMARY KEY (`pmID`), UNIQUE KEY `cron` (`pmHostID`,`pmMin`,`pmHour`,`pmDom`,`pmMonth`,`pmDow`,`pmAction`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'pmID' => 'int(11) NOT NULL',
                'pmHostID' => 'int(11) NOT NULL',
                'pmMin' => 'varchar(50) NOT NULL',
                'pmHour' => 'varchar(50) NOT NULL',
                'pmDom' => 'varchar(50) NOT NULL',
                'pmMonth' => 'varchar(50) NOT NULL',
                'pmDow' => 'varchar(50) NOT NULL',
                'pmAction' => 'enum(\'shutdown\',\'reboot\',\'wol\') NOT NULL',
                'pmOndemand' => 'enum(\'0\',\'1\') NOT NULL',
            ],
        ],
        'printerAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `printerAssoc` ( `paID` int(11) NOT NULL AUTO_INCREMENT, `paHostID` int(11) NOT NULL, `paPrinterID` int(11) NOT NULL, `paIsDefault` varchar(2) NOT NULL, `paAnon1` varchar(2) NOT NULL, `paAnon2` varchar(2) NOT NULL, `paAnon3` varchar(2) NOT NULL, `paAnon4` varchar(2) NOT NULL, `paAnon5` varchar(2) NOT NULL, PRIMARY KEY (`paID`), UNIQUE KEY `paHostID` (`paHostID`,`paPrinterID`), KEY `new_index1` (`paHostID`), KEY `new_index2` (`paPrinterID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'paID' => 'int(11) NOT NULL',
                'paHostID' => 'int(11) NOT NULL',
                'paPrinterID' => 'int(11) NOT NULL',
                'paIsDefault' => 'varchar(2) NOT NULL',
                'paAnon1' => 'varchar(2) NOT NULL',
                'paAnon2' => 'varchar(2) NOT NULL',
                'paAnon3' => 'varchar(2) NOT NULL',
                'paAnon4' => 'varchar(2) NOT NULL',
                'paAnon5' => 'varchar(2) NOT NULL',
            ],
        ],
        'printers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `printers` ( `pID` int(11) NOT NULL AUTO_INCREMENT, `pPort` longtext NOT NULL, `pDefFile` longtext NOT NULL, `pModel` varchar(250) NOT NULL, `pAlias` varchar(250) NOT NULL, `pConfig` varchar(10) NOT NULL, `pConfigFile` varchar(255) NOT NULL, `pIP` varchar(255) NOT NULL, `pAnon2` varchar(10) NOT NULL, `pAnon3` varchar(10) NOT NULL, `pAnon4` varchar(10) NOT NULL, `pAnon5` varchar(10) NOT NULL, `pDesc` longtext DEFAULT NULL, PRIMARY KEY (`pID`), UNIQUE KEY `pAlias` (`pAlias`), KEY `new_index1` (`pModel`), KEY `new_index2` (`pAlias`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'pID' => 'int(11) NOT NULL',
                'pPort' => 'longtext NOT NULL',
                'pDefFile' => 'longtext NOT NULL',
                'pModel' => 'varchar(250) NOT NULL',
                'pAlias' => 'varchar(250) NOT NULL',
                'pConfig' => 'varchar(10) NOT NULL',
                'pConfigFile' => 'varchar(255) NOT NULL',
                'pIP' => 'varchar(255) NOT NULL',
                'pAnon2' => 'varchar(10) NOT NULL',
                'pAnon3' => 'varchar(10) NOT NULL',
                'pAnon4' => 'varchar(10) NOT NULL',
                'pAnon5' => 'varchar(10) NOT NULL',
                'pDesc' => 'longtext DEFAULT NULL',
            ],
        ],
        'pxeMenu' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `pxeMenu` ( `pxeID` mediumint(9) NOT NULL AUTO_INCREMENT, `pxeName` varchar(100) NOT NULL, `pxeDesc` longtext NOT NULL, `pxeParams` longtext NOT NULL, `pxeRegOnly` int(11) NOT NULL DEFAULT 0, `pxeArgs` varchar(250) DEFAULT NULL, `pxeDefault` int(11) NOT NULL DEFAULT 0, `pxeHotKeyEnable` enum(\'0\',\'1\') NOT NULL, `pxeKeySequence` varchar(255) NOT NULL, PRIMARY KEY (`pxeID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'pxeID' => 'mediumint(9) NOT NULL',
                'pxeName' => 'varchar(100) NOT NULL',
                'pxeDesc' => 'longtext NOT NULL',
                'pxeParams' => 'longtext NOT NULL',
                'pxeRegOnly' => 'int(11) NOT NULL DEFAULT 0',
                'pxeArgs' => 'varchar(250) DEFAULT NULL',
                'pxeDefault' => 'int(11) NOT NULL DEFAULT 0',
                'pxeHotKeyEnable' => 'enum(\'0\',\'1\') NOT NULL',
                'pxeKeySequence' => 'varchar(255) NOT NULL',
            ],
        ],
        'rolePermissions' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `rolePermissions` ( `rpID` int(11) NOT NULL AUTO_INCREMENT, `rpRoleID` int(11) NOT NULL, `rpName` varchar(64) NOT NULL, PRIMARY KEY (`rpID`), UNIQUE KEY `rpRolePerm` (`rpRoleID`,`rpName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'rpID' => 'int(11) NOT NULL',
                'rpRoleID' => 'int(11) NOT NULL',
                'rpName' => 'varchar(64) NOT NULL',
            ],
        ],
        'roles' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `roles` ( `rID` int(11) NOT NULL AUTO_INCREMENT, `rName` varchar(255) NOT NULL, `rDesc` longtext NOT NULL, `rCreatedBy` varchar(40) NOT NULL, `rCreatedTime` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`rID`), UNIQUE KEY `rName` (`rName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'rID' => 'int(11) NOT NULL',
                'rName' => 'varchar(255) NOT NULL',
                'rDesc' => 'longtext NOT NULL',
                'rCreatedBy' => 'varchar(40) NOT NULL',
                'rCreatedTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
            ],
        ],
        'roleUserAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `roleUserAssoc` ( `ruaID` int(11) NOT NULL AUTO_INCREMENT, `ruaName` varchar(60) NOT NULL DEFAULT \'\', `ruaRoleID` int(11) NOT NULL, `ruaUserID` int(11) NOT NULL, PRIMARY KEY (`ruaID`), UNIQUE KEY `ruaRoleUser` (`ruaRoleID`,`ruaUserID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ruaID' => 'int(11) NOT NULL',
                'ruaName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'ruaRoleID' => 'int(11) NOT NULL',
                'ruaUserID' => 'int(11) NOT NULL',
            ],
        ],
        'roleUserGroupAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `roleUserGroupAssoc` ( `rugID` int(11) NOT NULL AUTO_INCREMENT, `rugName` varchar(60) NOT NULL DEFAULT \'\', `rugGroupID` int(11) NOT NULL, `rugRoleID` int(11) NOT NULL, PRIMARY KEY (`rugID`), UNIQUE KEY `rugGroupRole` (`rugGroupID`,`rugRoleID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'rugID' => 'int(11) NOT NULL',
                'rugName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'rugGroupID' => 'int(11) NOT NULL',
                'rugRoleID' => 'int(11) NOT NULL',
            ],
        ],
        'scheduledTasks' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `scheduledTasks` ( `stID` int(11) NOT NULL AUTO_INCREMENT, `stName` varchar(240) NOT NULL, `stDesc` longtext NOT NULL, `stType` varchar(24) NOT NULL, `stTaskTypeID` mediumint(9) NOT NULL, `stMinute` varchar(240) NOT NULL, `stHour` varchar(240) NOT NULL, `stDOM` varchar(240) NOT NULL, `stMonth` varchar(240) NOT NULL, `stDOW` varchar(240) NOT NULL, `stIsGroup` varchar(2) NOT NULL DEFAULT \'0\', `stGroupHostID` int(11) NOT NULL, `stImageID` int(11) NOT NULL, `stShutDown` varchar(2) NOT NULL, `stOther1` varchar(240) NOT NULL, `stOther2` varchar(240) NOT NULL, `stOther3` varchar(240) NOT NULL, `stOther4` varchar(240) NOT NULL, `stOther5` varchar(240) NOT NULL, `stDateTime` bigint(20) unsigned NOT NULL DEFAULT 0, `stActive` varchar(2) NOT NULL DEFAULT \'1\', PRIMARY KEY (`stID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'stID' => 'int(11) NOT NULL',
                'stName' => 'varchar(240) NOT NULL',
                'stDesc' => 'longtext NOT NULL',
                'stType' => 'varchar(24) NOT NULL',
                'stTaskTypeID' => 'mediumint(9) NOT NULL',
                'stMinute' => 'varchar(240) NOT NULL',
                'stHour' => 'varchar(240) NOT NULL',
                'stDOM' => 'varchar(240) NOT NULL',
                'stMonth' => 'varchar(240) NOT NULL',
                'stDOW' => 'varchar(240) NOT NULL',
                'stIsGroup' => 'varchar(2) NOT NULL DEFAULT \'0\'',
                'stGroupHostID' => 'int(11) NOT NULL',
                'stImageID' => 'int(11) NOT NULL',
                'stShutDown' => 'varchar(2) NOT NULL',
                'stOther1' => 'varchar(240) NOT NULL',
                'stOther2' => 'varchar(240) NOT NULL',
                'stOther3' => 'varchar(240) NOT NULL',
                'stOther4' => 'varchar(240) NOT NULL',
                'stOther5' => 'varchar(240) NOT NULL',
                'stDateTime' => 'bigint(20) unsigned NOT NULL DEFAULT 0',
                'stActive' => 'varchar(2) NOT NULL DEFAULT \'1\'',
            ],
        ],
        'schemaVersion' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `schemaVersion` ( `vID` int(11) NOT NULL AUTO_INCREMENT, `vValue` int(11) NOT NULL, PRIMARY KEY (`vID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'vID' => 'int(11) NOT NULL',
                'vValue' => 'int(11) NOT NULL',
            ],
        ],
        'siteGroupMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteGroupMembers` ( `sgmID` int(11) NOT NULL AUTO_INCREMENT, `sgmName` varchar(60) NOT NULL DEFAULT \'\', `sgmSiteID` int(11) NOT NULL, `sgmGroupID` int(11) NOT NULL, PRIMARY KEY (`sgmID`), UNIQUE KEY `sgmSiteGroup` (`sgmSiteID`,`sgmGroupID`), KEY `sgmGroupID` (`sgmGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sgmID' => 'int(11) NOT NULL',
                'sgmName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'sgmSiteID' => 'int(11) NOT NULL',
                'sgmGroupID' => 'int(11) NOT NULL',
            ],
        ],
        'siteHostMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteHostMembers` ( `shmID` int(11) NOT NULL AUTO_INCREMENT, `shmName` varchar(60) NOT NULL DEFAULT \'\', `shmSiteID` int(11) NOT NULL, `shmHostID` int(11) NOT NULL, PRIMARY KEY (`shmID`), UNIQUE KEY `shmSiteHost` (`shmSiteID`,`shmHostID`), KEY `shmHostID` (`shmHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'shmID' => 'int(11) NOT NULL',
                'shmName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'shmSiteID' => 'int(11) NOT NULL',
                'shmHostID' => 'int(11) NOT NULL',
            ],
        ],
        'siteRoleGrants' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteRoleGrants` ( `srgID` int(11) NOT NULL AUTO_INCREMENT, `srgName` varchar(60) NOT NULL DEFAULT \'\', `srgSiteID` int(11) NOT NULL, `srgRoleID` int(11) NOT NULL, PRIMARY KEY (`srgID`), UNIQUE KEY `srgSiteRole` (`srgSiteID`,`srgRoleID`), KEY `srgRoleID` (`srgRoleID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'srgID' => 'int(11) NOT NULL',
                'srgName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'srgSiteID' => 'int(11) NOT NULL',
                'srgRoleID' => 'int(11) NOT NULL',
            ],
        ],
        'sites' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `sites` ( `siteID` int(11) NOT NULL AUTO_INCREMENT, `siteName` varchar(255) NOT NULL, `siteDesc` longtext NOT NULL, `siteCatchAll` tinyint(1) unsigned DEFAULT NULL, PRIMARY KEY (`siteID`), UNIQUE KEY `siteName` (`siteName`), UNIQUE KEY `siteCatchAll` (`siteCatchAll`), CONSTRAINT `siteCatchAllIsOneOrNull` CHECK (`siteCatchAll` = 1) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'siteID' => 'int(11) NOT NULL',
                'siteName' => 'varchar(255) NOT NULL',
                'siteDesc' => 'longtext NOT NULL',
                'siteCatchAll' => 'tinyint(1) unsigned DEFAULT NULL',
            ],
        ],
        'siteUserGroupGrants' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteUserGroupGrants` ( `suggID` int(11) NOT NULL AUTO_INCREMENT, `suggName` varchar(60) NOT NULL DEFAULT \'\', `suggSiteID` int(11) NOT NULL, `suggGroupID` int(11) NOT NULL, PRIMARY KEY (`suggID`), UNIQUE KEY `suggSiteGroup` (`suggSiteID`,`suggGroupID`), KEY `suggGroupID` (`suggGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'suggID' => 'int(11) NOT NULL',
                'suggName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'suggSiteID' => 'int(11) NOT NULL',
                'suggGroupID' => 'int(11) NOT NULL',
            ],
        ],
        'siteUserGroupMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteUserGroupMembers` ( `sugmID` int(11) NOT NULL AUTO_INCREMENT, `sugmName` varchar(60) NOT NULL DEFAULT \'\', `sugmSiteID` int(11) NOT NULL, `sugmUserGroupID` int(11) NOT NULL, PRIMARY KEY (`sugmID`), UNIQUE KEY `sugmSiteUserGroup` (`sugmSiteID`,`sugmUserGroupID`), KEY `sugmUserGroupID` (`sugmUserGroupID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sugmID' => 'int(11) NOT NULL',
                'sugmName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'sugmSiteID' => 'int(11) NOT NULL',
                'sugmUserGroupID' => 'int(11) NOT NULL',
            ],
        ],
        'siteUserMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `siteUserMembers` ( `sumID` int(11) NOT NULL AUTO_INCREMENT, `sumName` varchar(60) NOT NULL DEFAULT \'\', `sumSiteID` int(11) NOT NULL, `sumUserID` int(11) NOT NULL, PRIMARY KEY (`sumID`), UNIQUE KEY `sumSiteUser` (`sumSiteID`,`sumUserID`), KEY `sumUserID` (`sumUserID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sumID' => 'int(11) NOT NULL',
                'sumName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'sumSiteID' => 'int(11) NOT NULL',
                'sumUserID' => 'int(11) NOT NULL',
            ],
        ],
        'snapinAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `snapinAssoc` ( `saID` int(11) NOT NULL AUTO_INCREMENT, `saHostID` int(11) NOT NULL, `saSnapinID` int(11) NOT NULL, `saSequence` int(11) NOT NULL DEFAULT 0, PRIMARY KEY (`saID`), UNIQUE KEY `saHostID` (`saHostID`,`saSnapinID`), UNIQUE KEY `saSnapinID` (`saSnapinID`,`saHostID`), KEY `new_index` (`saHostID`), KEY `new_index1` (`saSnapinID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'saID' => 'int(11) NOT NULL',
                'saHostID' => 'int(11) NOT NULL',
                'saSnapinID' => 'int(11) NOT NULL',
                'saSequence' => 'int(11) NOT NULL DEFAULT 0',
            ],
        ],
        'snapinGroupAssoc' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `snapinGroupAssoc` ( `sgaID` mediumint(9) NOT NULL AUTO_INCREMENT, `sgaSnapinID` mediumint(9) NOT NULL, `sgaStorageGroupID` mediumint(9) NOT NULL, `sgaPrimary` enum(\'0\',\'1\') NOT NULL, PRIMARY KEY (`sgaID`), UNIQUE KEY `sgaSnapinID` (`sgaSnapinID`,`sgaStorageGroupID`), UNIQUE KEY `sgaStorageGroupID` (`sgaStorageGroupID`,`sgaSnapinID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sgaID' => 'mediumint(9) NOT NULL',
                'sgaSnapinID' => 'mediumint(9) NOT NULL',
                'sgaStorageGroupID' => 'mediumint(9) NOT NULL',
                'sgaPrimary' => 'enum(\'0\',\'1\') NOT NULL',
            ],
        ],
        'snapinJobs' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `snapinJobs` ( `sjID` int(11) NOT NULL AUTO_INCREMENT, `sjHostID` int(11) NOT NULL, `sjStateID` int(11) NOT NULL, `sjAbortOnFail` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `sjCreateTime` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`sjID`), KEY `new_index` (`sjHostID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sjID' => 'int(11) NOT NULL',
                'sjHostID' => 'int(11) NOT NULL',
                'sjStateID' => 'int(11) NOT NULL',
                'sjAbortOnFail' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'sjCreateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
            ],
        ],
        'snapins' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `snapins` ( `sID` int(11) NOT NULL AUTO_INCREMENT, `sName` varchar(200) NOT NULL, `sDesc` longtext NOT NULL, `sFilePath` longtext NOT NULL, `sArgs` longtext NOT NULL, `sCreateDate` timestamp NOT NULL DEFAULT current_timestamp(), `sCreator` varchar(200) NOT NULL, `sReboot` varchar(1) NOT NULL, `sRunWith` varchar(245) NOT NULL, `sRunWithArgs` varchar(200) NOT NULL, `sAnon3` varchar(45) NOT NULL, `snapinProtect` mediumint(9) NOT NULL, `sEnabled` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `sReplicate` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `sShutdown` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `sHideLog` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `sTimeout` int(11) NOT NULL DEFAULT 0, `sPackType` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `sHash` varchar(255) NOT NULL DEFAULT \'\', `sSize` bigint(20) NOT NULL DEFAULT 0, PRIMARY KEY (`sID`), UNIQUE KEY `sName` (`sName`), KEY `new_index` (`sName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'sID' => 'int(11) NOT NULL',
                'sName' => 'varchar(200) NOT NULL',
                'sDesc' => 'longtext NOT NULL',
                'sFilePath' => 'longtext NOT NULL',
                'sArgs' => 'longtext NOT NULL',
                'sCreateDate' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'sCreator' => 'varchar(200) NOT NULL',
                'sReboot' => 'varchar(1) NOT NULL',
                'sRunWith' => 'varchar(245) NOT NULL',
                'sRunWithArgs' => 'varchar(200) NOT NULL',
                'sAnon3' => 'varchar(45) NOT NULL',
                'snapinProtect' => 'mediumint(9) NOT NULL',
                'sEnabled' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'sReplicate' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'sShutdown' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'sHideLog' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'sTimeout' => 'int(11) NOT NULL DEFAULT 0',
                'sPackType' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'sHash' => 'varchar(255) NOT NULL DEFAULT \'\'',
                'sSize' => 'bigint(20) NOT NULL DEFAULT 0',
            ],
        ],
        'snapinTasks' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `snapinTasks` ( `stID` int(11) NOT NULL AUTO_INCREMENT, `stJobID` int(11) NOT NULL, `stState` int(11) NOT NULL, `stCheckinDate` timestamp NOT NULL DEFAULT current_timestamp(), `stCompleteDate` datetime NOT NULL, `stSnapinID` int(11) NOT NULL, `stSequence` int(11) NOT NULL DEFAULT 0, `stReturnCode` int(11) NOT NULL, `stReturnDetails` varchar(250) NOT NULL, PRIMARY KEY (`stID`), UNIQUE KEY `stJobID` (`stJobID`,`stSnapinID`), KEY `new_index` (`stJobID`), KEY `new_index1` (`stState`), KEY `new_index2` (`stSnapinID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'stID' => 'int(11) NOT NULL',
                'stJobID' => 'int(11) NOT NULL',
                'stState' => 'int(11) NOT NULL',
                'stCheckinDate' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'stCompleteDate' => 'datetime NOT NULL',
                'stSnapinID' => 'int(11) NOT NULL',
                'stSequence' => 'int(11) NOT NULL DEFAULT 0',
                'stReturnCode' => 'int(11) NOT NULL',
                'stReturnDetails' => 'varchar(250) NOT NULL',
            ],
        ],
        'supportedOS' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `supportedOS` ( `osID` int(10) unsigned NOT NULL AUTO_INCREMENT, `osName` varchar(150) NOT NULL, `osValue` int(10) unsigned NOT NULL, PRIMARY KEY (`osID`), UNIQUE KEY `osName` (`osName`), KEY `new_index` (`osValue`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'osID' => 'int(10) unsigned NOT NULL',
                'osName' => 'varchar(150) NOT NULL',
                'osValue' => 'int(10) unsigned NOT NULL',
            ],
        ],
        'taskLog' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `taskLog` ( `id` mediumint(9) NOT NULL AUTO_INCREMENT, `taskID` int(11) NOT NULL, `taskStateID` mediumint(9) NOT NULL, `ip` varchar(15) NOT NULL, `createTime` timestamp NOT NULL DEFAULT current_timestamp(), `createdBy` varchar(30) NOT NULL, `logType` varchar(16) NOT NULL DEFAULT \'state\', `logText` text DEFAULT NULL, `logHostID` int(11) DEFAULT NULL, `logHostName` varchar(16) NOT NULL DEFAULT \'\', `logTaskTypeName` varchar(30) NOT NULL DEFAULT \'\', PRIMARY KEY (`id`), KEY `taskID` (`taskID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'id' => 'mediumint(9) NOT NULL',
                'taskID' => 'int(11) NOT NULL',
                'taskStateID' => 'mediumint(9) NOT NULL',
                'ip' => 'varchar(15) NOT NULL',
                'createTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'createdBy' => 'varchar(30) NOT NULL',
                'logType' => 'varchar(16) NOT NULL DEFAULT \'state\'',
                'logText' => 'text DEFAULT NULL',
                'logHostID' => 'int(11) DEFAULT NULL',
                'logHostName' => 'varchar(16) NOT NULL DEFAULT \'\'',
                'logTaskTypeName' => 'varchar(30) NOT NULL DEFAULT \'\'',
            ],
        ],
        'tasks' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `tasks` ( `taskID` int(11) NOT NULL AUTO_INCREMENT, `taskName` varchar(250) NOT NULL, `taskCreateTime` timestamp NOT NULL DEFAULT current_timestamp(), `taskCheckIn` datetime NOT NULL, `taskHostID` int(11) NOT NULL, `taskImageID` int(11) NOT NULL, `taskStateID` int(11) NOT NULL, `taskIsDebug` mediumint(9) NOT NULL, `taskCreateBy` varchar(200) NOT NULL, `taskForce` varchar(1) NOT NULL, `taskScheduledStartTime` datetime NOT NULL, `taskTypeID` mediumint(9) NOT NULL, `taskPCT` int(10) unsigned zerofill NOT NULL, `taskBPM` varchar(250) NOT NULL, `taskTimeElapsed` varchar(250) NOT NULL, `taskTimeRemaining` varchar(250) NOT NULL, `taskDataCopied` varchar(250) NOT NULL, `taskPercentText` varchar(250) NOT NULL, `taskDataTotal` varchar(250) NOT NULL, `taskNFSGroupID` int(11) NOT NULL, `taskNFSMemberID` int(11) NOT NULL, `taskNFSFailures` char(1) NOT NULL, `taskLastMemberID` int(11) NOT NULL, `taskWOL` enum(\'0\',\'1\') NOT NULL, `taskPassreset` varchar(250) NOT NULL, `taskShutdown` char(1) NOT NULL, `taskBypassBitlocker` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `taskStateChangedTime` datetime DEFAULT NULL, PRIMARY KEY (`taskID`), KEY `new_index` (`taskHostID`), KEY `new_index1` (`taskCheckIn`), KEY `new_index2` (`taskStateID`), KEY `new_index3` (`taskForce`), KEY `new_index4` (`taskTypeID`), KEY `new_index5` (`taskNFSGroupID`), KEY `new_index6` (`taskNFSMemberID`), KEY `new_index7` (`taskNFSFailures`), KEY `new_index8` (`taskLastMemberID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'taskID' => 'int(11) NOT NULL',
                'taskName' => 'varchar(250) NOT NULL',
                'taskCreateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'taskCheckIn' => 'datetime NOT NULL',
                'taskHostID' => 'int(11) NOT NULL',
                'taskImageID' => 'int(11) NOT NULL',
                'taskStateID' => 'int(11) NOT NULL',
                'taskIsDebug' => 'mediumint(9) NOT NULL',
                'taskCreateBy' => 'varchar(200) NOT NULL',
                'taskForce' => 'varchar(1) NOT NULL',
                'taskScheduledStartTime' => 'datetime NOT NULL',
                'taskTypeID' => 'mediumint(9) NOT NULL',
                'taskPCT' => 'int(10) unsigned zerofill NOT NULL',
                'taskBPM' => 'varchar(250) NOT NULL',
                'taskTimeElapsed' => 'varchar(250) NOT NULL',
                'taskTimeRemaining' => 'varchar(250) NOT NULL',
                'taskDataCopied' => 'varchar(250) NOT NULL',
                'taskPercentText' => 'varchar(250) NOT NULL',
                'taskDataTotal' => 'varchar(250) NOT NULL',
                'taskNFSGroupID' => 'int(11) NOT NULL',
                'taskNFSMemberID' => 'int(11) NOT NULL',
                'taskNFSFailures' => 'char(1) NOT NULL',
                'taskLastMemberID' => 'int(11) NOT NULL',
                'taskWOL' => 'enum(\'0\',\'1\') NOT NULL',
                'taskPassreset' => 'varchar(250) NOT NULL',
                'taskShutdown' => 'char(1) NOT NULL',
                'taskBypassBitlocker' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'taskStateChangedTime' => 'datetime DEFAULT NULL',
            ],
        ],
        'taskStates' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `taskStates` ( `tsID` int(11) NOT NULL AUTO_INCREMENT, `tsName` varchar(30) NOT NULL, `tsDescription` text NOT NULL, `tsOrder` tinyint(4) NOT NULL DEFAULT 0, `tsIcon` varchar(255) NOT NULL, PRIMARY KEY (`tsID`), UNIQUE KEY `tsName` (`tsName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'tsID' => 'int(11) NOT NULL',
                'tsName' => 'varchar(30) NOT NULL',
                'tsDescription' => 'text NOT NULL',
                'tsOrder' => 'tinyint(4) NOT NULL DEFAULT 0',
                'tsIcon' => 'varchar(255) NOT NULL',
            ],
        ],
        'taskTypes' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `taskTypes` ( `ttID` mediumint(9) NOT NULL AUTO_INCREMENT, `ttName` varchar(30) NOT NULL, `ttDescription` text NOT NULL, `ttIcon` varchar(30) NOT NULL, `ttKernel` varchar(100) NOT NULL, `ttKernelArgs` text NOT NULL, `ttType` enum(\'fog\',\'user\') NOT NULL DEFAULT \'user\', `ttIsAdvanced` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\', `ttIsAccess` enum(\'both\',\'host\',\'group\') NOT NULL DEFAULT \'both\', `ttInitrd` longtext NOT NULL, PRIMARY KEY (`ttID`), UNIQUE KEY `ttName` (`ttName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ttID' => 'mediumint(9) NOT NULL',
                'ttName' => 'varchar(30) NOT NULL',
                'ttDescription' => 'text NOT NULL',
                'ttIcon' => 'varchar(30) NOT NULL',
                'ttKernel' => 'varchar(100) NOT NULL',
                'ttKernelArgs' => 'text NOT NULL',
                'ttType' => 'enum(\'fog\',\'user\') NOT NULL DEFAULT \'user\'',
                'ttIsAdvanced' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'0\'',
                'ttIsAccess' => 'enum(\'both\',\'host\',\'group\') NOT NULL DEFAULT \'both\'',
                'ttInitrd' => 'longtext NOT NULL',
            ],
        ],
        'userAuths' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `userAuths` ( `uaID` int(11) NOT NULL AUTO_INCREMENT, `uaUserID` int(11) NOT NULL, `uaExpireDate` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), `uaIsExpired` int(11) NOT NULL DEFAULT 0, `uaSelectorHash` varchar(255) NOT NULL, `uaPasswordHash` varchar(255) NOT NULL, PRIMARY KEY (`uaID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'uaID' => 'int(11) NOT NULL',
                'uaUserID' => 'int(11) NOT NULL',
                'uaExpireDate' => 'timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()',
                'uaIsExpired' => 'int(11) NOT NULL DEFAULT 0',
                'uaSelectorHash' => 'varchar(255) NOT NULL',
                'uaPasswordHash' => 'varchar(255) NOT NULL',
            ],
        ],
        'userCleanup' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `userCleanup` ( `ucID` int(11) NOT NULL AUTO_INCREMENT, `ucName` varchar(254) NOT NULL, PRIMARY KEY (`ucID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ucID' => 'int(11) NOT NULL',
                'ucName' => 'varchar(254) NOT NULL',
            ],
        ],
        'userGroupMembers' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `userGroupMembers` ( `ugmID` int(11) NOT NULL AUTO_INCREMENT, `ugmName` varchar(60) NOT NULL DEFAULT \'\', `ugmGroupID` int(11) NOT NULL, `ugmUserID` int(11) NOT NULL, PRIMARY KEY (`ugmID`), UNIQUE KEY `ugmGroupUser` (`ugmGroupID`,`ugmUserID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ugmID' => 'int(11) NOT NULL',
                'ugmName' => 'varchar(60) NOT NULL DEFAULT \'\'',
                'ugmGroupID' => 'int(11) NOT NULL',
                'ugmUserID' => 'int(11) NOT NULL',
            ],
        ],
        'userGroups' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `userGroups` ( `ugID` int(11) NOT NULL AUTO_INCREMENT, `ugName` varchar(255) NOT NULL, `ugDesc` longtext NOT NULL, `ugCreatedBy` varchar(40) NOT NULL, `ugCreatedTime` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`ugID`), UNIQUE KEY `ugName` (`ugName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'ugID' => 'int(11) NOT NULL',
                'ugName' => 'varchar(255) NOT NULL',
                'ugDesc' => 'longtext NOT NULL',
                'ugCreatedBy' => 'varchar(40) NOT NULL',
                'ugCreatedTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
            ],
        ],
        'users' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `users` ( `uId` int(11) NOT NULL AUTO_INCREMENT, `uName` varchar(255) DEFAULT NULL, `uPass` longtext NOT NULL, `uCreateDate` datetime NOT NULL, `uCreateBy` varchar(255) DEFAULT NULL, `uType` int(11) NOT NULL, `uDisplay` varchar(255) NOT NULL, `uAllowAPI` enum(\'0\',\'1\') NOT NULL DEFAULT \'1\', `uAPIToken` varchar(255) NOT NULL, `uAuthSource` varchar(32) NOT NULL DEFAULT \'\', PRIMARY KEY (`uId`), UNIQUE KEY `name` (`uName`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'uId' => 'int(11) NOT NULL',
                'uName' => 'varchar(255) DEFAULT NULL',
                'uPass' => 'longtext NOT NULL',
                'uCreateDate' => 'datetime NOT NULL',
                'uCreateBy' => 'varchar(255) DEFAULT NULL',
                'uType' => 'int(11) NOT NULL',
                'uDisplay' => 'varchar(255) NOT NULL',
                'uAllowAPI' => 'enum(\'0\',\'1\') NOT NULL DEFAULT \'1\'',
                'uAPIToken' => 'varchar(255) NOT NULL',
                'uAuthSource' => 'varchar(32) NOT NULL DEFAULT \'\'',
            ],
        ],
        'userTracking' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `userTracking` ( `utID` int(11) NOT NULL AUTO_INCREMENT, `utHostID` int(11) NOT NULL, `utUserName` varchar(50) NOT NULL, `utAction` varchar(2) NOT NULL, `utDateTime` timestamp NOT NULL DEFAULT current_timestamp(), `utDesc` varchar(250) NOT NULL, `utDate` date NOT NULL, `utAnon3` varchar(2) NOT NULL, PRIMARY KEY (`utID`), KEY `new_index` (`utHostID`), KEY `new_index1` (`utUserName`), KEY `new_index2` (`utAction`), KEY `new_index3` (`utDateTime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'utID' => 'int(11) NOT NULL',
                'utHostID' => 'int(11) NOT NULL',
                'utUserName' => 'varchar(50) NOT NULL',
                'utAction' => 'varchar(2) NOT NULL',
                'utDateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'utDesc' => 'varchar(250) NOT NULL',
                'utDate' => 'date NOT NULL',
                'utAnon3' => 'varchar(2) NOT NULL',
            ],
        ],
        'virus' => [
            'create' => 'CREATE TABLE IF NOT EXISTS `virus` ( `vID` int(11) NOT NULL AUTO_INCREMENT, `vName` varchar(250) NOT NULL, `vHostMAC` varchar(50) NOT NULL, `vOrigFile` longtext NOT NULL, `vDateTime` timestamp NOT NULL DEFAULT current_timestamp(), `vMode` varchar(5) NOT NULL, `vAnon2` varchar(50) NOT NULL, PRIMARY KEY (`vID`), KEY `new_index` (`vHostMAC`), KEY `new_index2` (`vDateTime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC',
            'columns' => [
                'vID' => 'int(11) NOT NULL',
                'vName' => 'varchar(250) NOT NULL',
                'vHostMAC' => 'varchar(50) NOT NULL',
                'vOrigFile' => 'longtext NOT NULL',
                'vDateTime' => 'timestamp NOT NULL DEFAULT current_timestamp()',
                'vMode' => 'varchar(5) NOT NULL',
                'vAnon2' => 'varchar(50) NOT NULL',
            ],
        ],
    ],
];
