(function($) {
    $('#host-export-table').registerExportTable([
        {data: 'primac'},
        {data: 'name'},
        {data: 'description', visible: false},
        {data: 'ip', visible: false},
        {data: 'imageID', visible: false},
        {data: 'building', visible: false},
        {data: 'createdTime', visible: false},
        {data: 'deployed', visible: false},
        {data: 'createdBy', visible: false},
        {data: 'useAD', visible: false},
        {data: 'ADDomain', visible: false},
        {data: 'ADOU', visible: false},
        {data: 'ADUser', visible: false},
        {data: 'printerLevel', visible: false},
        {data: 'kernelArgs', visible: false},
        {data: 'kernel', visible: false},
        {data: 'kernelDevice', visible: false},
        {data: 'init', visible: false},
        {data: 'pending', visible: false},
        {data: 'pingstatus', visible: false},
        {data: 'pingmethod', visible: false},
        {data: 'lastping', visible: false},
        {data: 'lastcheckin', visible: false},
        {data: 'archID', visible: false},
        {data: 'sbstate', visible: false},
        {data: 'sbstatetime', visible: false},
        {data: 'sbenrolled', visible: false},
        {data: 'sbenrollcert', visible: false},
        {data: 'sbenrollvia', visible: false},
        {data: 'biosexit', visible: false},
        {data: 'efiexit', visible: false},
        {data: 'enforce', visible: false},
        {data: 'tokenlock', visible: false},
        {data: 'agentFingerprint', visible: false},
        {data: 'agentNotAfter', visible: false},
        {data: 'agentVersion', visible: false},
        {data: 'agentCheckin', visible: false},
        {data: 'associations', visible: false}
    ], {order: [[1, 'asc']]});
})(jQuery);
