#!/bin/sh
#
# Start the network....
#

if [ -n "$has_usb_nic" ]; then
	echo "Please unplug your device and replug it into the usb port";
	echo -n "Please press enter key to connect [Enter]";
	read;
	echo "Sleeping for 5 seconds to allow USB to sync back with system";
	sleep 5;
fi

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

