#!/bin/bash
#
#
# rc.single     This file is executed by init when it goes into runlevel
#               1, which is the administrative state. It kills all
#               deamons and then puts the system into single user mode.
#               Note that the file systems are kept mounted.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for RHS Linux by Damien Neil
#               Modified for FOG by Chuck Syperski
#
if [[ $mdraid == true ]]; then
    mdadm --assemble --scan
    mdadm --incremental --run --scan
fi
[[ -n $keymap ]] && loadkeys $keymap
if [[ -z $isdebug && $mode != +(*debug*) ]]; then
    fog
    [[ $shutdown -eq 1 ]] && poweroff || reboot -f
    exit 0
fi
fog.debug
